export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: { Row: { id: string; full_name: string | null; username: string | null; avatar_url: string | null; role: 'student' | 'writer' | 'editor' | 'admin'; account_status: 'pending' | 'approved' | 'rejected' | 'suspended'; onboarding_complete: boolean; created_at: string; updated_at: string }; Insert: Partial<Omit<Database['public']['Tables']['profiles']['Row'], 'id'>> & { id: string }; Update: Partial<Database['public']['Tables']['profiles']['Row']>; Relationships: [] };
      public_profiles: { Row: { id: string; display_name: string; avatar_url: string | null; bio: string | null; specialties: string[] | null; verified: boolean; rating: number; review_count: number; completed_projects: number; average_delivery_days: number | null; accuracy_score: number | null; created_at: string; updated_at: string }; Insert: Omit<Database['public']['Tables']['public_profiles']['Row'], 'created_at' | 'updated_at'> & Partial<Pick<Database['public']['Tables']['public_profiles']['Row'], 'created_at' | 'updated_at'>>; Update: Partial<Database['public']['Tables']['public_profiles']['Row']>; Relationships: [] };
      institutions: { Row: { id: string; name: string; country: string | null; created_at: string }; Insert: { id?: string; name: string; country?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['institutions']['Insert']>; Relationships: [] };
      departments: { Row: { id: string; institution_id: string; name: string; faculty: string | null; created_at: string }; Insert: { id?: string; institution_id: string; name: string; faculty?: string | null; created_at?: string }; Update: Partial<Database['public']['Tables']['departments']['Insert']>; Relationships: [] };
      project_specifications: { Row: { id: string; student_id: string; project_title: string; student_full_name: string | null; matric_number: string | null; institution_id: string | null; department_id: string | null; degree_award: string | null; supervisor_name: string | null; hod_name: string | null; submission_month_year: string | null; project_type: string | null; plan: 'basic' | 'standard' | 'premium' | null; page_requirement: string | null; citation_style: string | null; font: string | null; font_size: string | null; line_spacing: string | null; margins: string | null; alignment: string | null; page_numbering: string | null; chapter_headings: string | null; chapter_count: number | null; standards_bodies: string | null; core_subject_matter: string | null; target_outcome: string | null; real_data: string | null; scope: string | null; special_instructions: string | null; confirmed: boolean; confirmed_at: string | null; created_at: string; updated_at: string }; Insert: Partial<Omit<Database['public']['Tables']['project_specifications']['Row'], 'id' | 'student_id' | 'project_title'>> & { student_id: string; project_title: string }; Update: Partial<Database['public']['Tables']['project_specifications']['Row']>; Relationships: [] };
      projects: { Row: { id: string; student_id: string; writer_id: string | null; editor_id: string | null; specification_id: string | null; title: string; plan: 'basic' | 'standard' | 'premium'; status: string; price_ngn: number; revision_limit: number; revisions_used: number; deadline_at: string | null; submitted_at: string | null; approved_at: string | null; completed_at: string | null; created_at: string; updated_at: string }; Insert: Partial<Omit<Database['public']['Tables']['projects']['Row'], 'id' | 'student_id' | 'title' | 'plan'>> & { student_id: string; title: string; plan: 'basic' | 'standard' | 'premium' }; Update: Partial<Database['public']['Tables']['projects']['Row']>; Relationships: [] };
      project_files: { Row: { id: string; project_id: string; uploaded_by: string; file_type: string; storage_path: string | null; drive_url: string | null; version: number; is_customer_visible: boolean; created_at: string }; Insert: Omit<Database['public']['Tables']['project_files']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['project_files']['Insert']>; Relationships: [] };
      project_revisions: { Row: { id: string; project_id: string; requested_by: string; accepted_by: string | null; status: 'pending' | 'accepted' | 'in_progress' | 'completed' | 'declined'; request_text: string; points_cost: number; created_at: string; accepted_at: string | null; completed_at: string | null }; Insert: Omit<Database['public']['Tables']['project_revisions']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['project_revisions']['Insert']>; Relationships: [] };
      reviews: { Row: { id: string; project_id: string; reviewer_id: string; writer_id: string; rating: number; review_text: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['reviews']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['reviews']['Insert']>; Relationships: [] };
      payments: { Row: { id: string; project_id: string; student_id: string; provider: string; reference: string; amount_ngn: number; status: string; paid_at: string | null; metadata: Json | null; created_at: string }; Insert: Omit<Database['public']['Tables']['payments']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['payments']['Insert']>; Relationships: [] };
      wallets: { Row: { user_id: string; balance_ngn: number; points_balance: number; updated_at: string }; Insert: { user_id: string; balance_ngn?: number; points_balance?: number; updated_at?: string }; Update: Partial<Database['public']['Tables']['wallets']['Insert']>; Relationships: [] };
      wallet_transactions: { Row: { id: string; user_id: string; transaction_type: string; amount_ngn: number; points: number; reference: string | null; project_id: string | null; metadata: Json | null; created_at: string }; Insert: Omit<Database['public']['Tables']['wallet_transactions']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['wallet_transactions']['Insert']>; Relationships: [] };
      point_transactions: { Row: { id: string; user_id: string; direction: 'credit' | 'debit'; points: number; reason: string; project_id: string | null; reference: string | null; created_at: string }; Insert: Omit<Database['public']['Tables']['point_transactions']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['point_transactions']['Insert']>; Relationships: [] };
      withdrawals: { Row: { id: string; user_id: string; amount_ngn: number; transaction_fee_ngn: number; status: string; bank_name: string | null; account_name: string | null; account_number_last4: string | null; created_at: string; processed_at: string | null }; Insert: Omit<Database['public']['Tables']['withdrawals']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['withdrawals']['Insert']>; Relationships: [] };
      notifications: { Row: { id: string; user_id: string; type: string; title: string; body: string | null; read_at: string | null; metadata: Json | null; created_at: string }; Insert: Omit<Database['public']['Tables']['notifications']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['notifications']['Insert']>; Relationships: [] };
      writer_applications: { Row: { id: string; user_id: string; status: 'pending' | 'approved' | 'rejected' | 'suspended'; bio: string | null; specialties: string[] | null; academic_qualifications: string | null; portfolio_url: string | null; created_at: string; reviewed_at: string | null; reviewed_by: string | null }; Insert: Omit<Database['public']['Tables']['writer_applications']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Update: Partial<Database['public']['Tables']['writer_applications']['Insert']>; Relationships: [] };
      editor_applications: { Row: { id: string; user_id: string; status: 'pending' | 'approved' | 'rejected' | 'suspended'; bio: string | null; specialties: string[] | null; qualifications: string | null; created_at: string; reviewed_at: string | null; reviewed_by: string | null }; Insert: Omit<Database['public']['Tables']['editor_applications']['Row'], 'id' | 'created_at'> & { id?: string; created_at?: string }; Relationships: [] };
    };
    Views: Record<string, never>;
    Functions: Record<string, { Args: Record<string, unknown>; Returns: unknown }>;
    Enums: { application_status: 'pending' | 'approved' | 'rejected' | 'suspended'; plan_type: 'basic' | 'standard' | 'premium'; project_status: string; review_status: 'pending' | 'accepted' | 'in_progress' | 'completed' | 'declined'; user_role: 'student' | 'writer' | 'editor' | 'admin' };
    CompositeTypes: Record<string, never>;
  };
};