import type {Handler} from '@netlify/functions';

type Institution={name:string;ownership:string;institution_type:'university'|'polytechnic'};
const clean=(html:string)=>html.replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&amp;/g,'&').replace(/&#39;/g,"'").replace(/&nbsp;/g,' ').replace(/&ndash;/g,'–').replace(/&quot;/g,'"').replace(/\s+/g,' ').trim();
async function fetchText(url:string){const r=await fetch(url,{headers:{'user-agent':'Finalyzed-National-Institution-Sync/2.0','accept':'text/html,application/xhtml+xml'}});if(!r.ok)throw new Error(url+' returned '+r.status);return r.text();}
function parseRows(html:string,ownership:string):Institution[]{const out:Institution[]=[];for(const m of html.matchAll(/<tr[^>]*>[\s\S]*?<td[^>]*>\s*\d+\.?\s*<\/td>[\s\S]*?<td[^>]*>([\s\S]*?)<\/td>/gi)){const name=clean(m[1]);if(name&&name.length>3&&!/^(s\/?n|serial|institution|polytechnic)$/i.test(name))out.push({name:name.replace(/\s*\([^)]*\)\s*$/,''),ownership,institution_type:'polytechnic'});}return out;}
const fallback:Institution[]=[
['Akanu Ibiam Federal Polytechnic, Unwana','federal'],['Auchi Polytechnic','federal'],['Federal Polytechnic, Ado-Ekiti','federal'],['Federal Polytechnic, Bauchi','federal'],['Federal Polytechnic, Bida','federal'],['Federal Polytechnic, Damaturu','federal'],['Federal Polytechnic, Ede','federal'],['Federal Polytechnic, Idah','federal'],['Federal Polytechnic, Ilaro','federal'],['Federal Polytechnic, Kaura Namoda','federal'],['Federal Polytechnic, Mubi','federal'],['Federal Polytechnic, Nasarawa','federal'],['Federal Polytechnic, Nekede','federal'],['Federal Polytechnic, Offa','federal'],['Federal Polytechnic, Oko','federal'],['Federal Polytechnic, Bali','federal'],['Federal Polytechnic, Ekowe','federal'],['Federal Polytechnic, Ile-Oluji','federal'],['Federal Polytechnic, Daura','federal'],['Hussaini Adamu Federal Polytechnic, Kazaure','federal'],['Kaduna Polytechnic','federal'],['Yaba College of Technology','federal'],['Al-Hikma Polytechnic','private'],['Allover Central Polytechnic','private'],['Ashi Polytechnic','private'],['Best Solution Polytechnic','private'],['Bolmor Polytechnic','private'],['Crown Polytechnic','private'],['Dorben Polytechnic','private'],['Fidei Polytechnic','private'],['Gateway ICT Polytechnic','private'],['Heritage Polytechnic','private'],['Igbajo Polytechnic','private'],['Lagos City Polytechnic','private'],['Moshood Abiola Polytechnic','state'],['Kwara State Polytechnic','state'],['Lagos State Polytechnic','state'],['Ogun State Institute of Technology','state'],['Osun State Polytechnic, Iree','state'],['Rufus Giwa Polytechnic','state'],['The Polytechnic, Ibadan','state']
].map(([name,ownership])=>({name,ownership,institution_type:'polytechnic'}));

export const handler:Handler=async(event)=>{
 if(event.httpMethod!=='GET')return{statusCode:405,body:JSON.stringify({error:'Method not allowed'})};
 const institutions:Institution[]=[];
 try{
  const nucSources:[string,string][]=[['federal','https://www.nuc.edu.ng/nigerian-univerisities/federal-univeristies/'],['state','https://www.nuc.edu.ng/nigerian-univerisities/state-univerisity/'],['private','https://www.nuc.edu.ng/nigerian-univeristies/private-univeristies/']];
  for(const [ownership,url] of nucSources){try{const html=await fetchText(url);for(const m of html.matchAll(/<tr[^>]*>\s*<td[^>]*>\s*\d+\s*<\/td>\s*<td[^>]*>([\s\S]*?)<\/td>/gi)){const name=clean(m[1]);if(name&&!/universities$/i.test(name))institutions.push({name,ownership,institution_type:'university'});}}catch{}}
  try{const root='https://www.nbte.gov.ng/nbte/approved%20institutions';const html=await fetchText(root);const links=[...html.matchAll(/<a[^>]+href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)];for(const type of ['federal','state','private']){const link=links.find(x=>new RegExp(type+'\\s+polytechnics','i').test(clean(x[2])));if(link){const url=new URL(link[1],root).href;const rows=parseRows(await fetchText(url),type);institutions.push(...rows);}}}catch{institutions.push(...fallback)}
  if(institutions.filter(x=>x.institution_type==='polytechnic').length<10)institutions.push(...fallback);
  const unique=[...new Map(institutions.map(x=>[x.name.toLowerCase(),x])).values()].sort((a,b)=>a.name.localeCompare(b.name));
  return{statusCode:200,headers:{'content-type':'application/json','cache-control':'public,max-age=86400'},body:JSON.stringify({source:'NUC + NBTE',count:unique.length,institutions:unique})};
 }catch(e){return{statusCode:502,body:JSON.stringify({error:e instanceof Error?e.message:'Unable to load national institution catalogue.'})}}
};