import React,{useEffect,useState} from 'react';
import {ShieldAlert,Users,FileText,DollarSign,WalletCards,ArrowRight,RefreshCw,TrendingUp} from 'lucide-react';
import {Link} from 'react-router-dom';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import DashboardAnalytics from '../components/DashboardAnalytics';
export default function AdminDashboard(){const {user,userData}=useAuth();const [projects,setProjects]=useState<any[]>([]),[payments,setPayments]=useState<any[]>([]),[stats,setStats]=useState<any>({}),[analytics,setAnalytics]=useState<any>({}),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const [p,pay,s,a]=await Promise.all([supabase.from('projects').select('id,status,created_at,price_ngn'),supabase.from('payments').select('status,amount_ngn,created_at').limit(300),supabase.rpc('finalyzed_admin_stats'),supabase.rpc('finalyzed_admin_analytics')]);setProjects(p.data||[]);setPayments(pay.data||[]);setStats(s.data||{});setAnalytics(a.data||{});setLoading(false)};useEffect(()=>{if(user&&userData?.role==='admin')void load()},[user,userData]);if(userData?.role!=='admin')return <div className="p-8 text-center text-red-500">Administrator access required.</div>;if(loading)return <div className="p-8 text-center text-muted-foreground">Loading admin portal…</div>;
 const active=projects.filter(p=>!['completed','cancelled'].includes(p.status)).length;const money=(n:number)=>'₦'+Number(n||0).toLocaleString('en-NG');
 return <div className="space-y-5"><header className="flex items-end justify-between gap-4"><div><span className="mono-label text-primary flex items-center gap-2"><ShieldAlert className="w-4 h-4"/>Super Admin Portal</span><h1 className="text-2xl md:text-3xl font-bold mt-1">FINALYZED <span className="font-light">OPERATIONS</span></h1><p className="text-sm text-muted-foreground mt-1">A compact command overview. Detailed records live in the Admin Center.</p></div><button onClick={()=>void load()} className="btn-secondary p-2.5" aria-label="Refresh"><RefreshCw className="w-4 h-4"/></button></header>
 <div className="grid grid-cols-2 lg:grid-cols-5 gap-2.5"><Metric icon={<Users/>} label="Students" value={stats.students||0}/><Metric icon={<Users/>} label="Writers" value={stats.approved_writers||0}/><Metric icon={<Users/>} label="Editors" value={stats.approved_managers||0}/><Metric icon={<FileText/>} label="Active projects" value={active}/><Metric icon={<DollarSign/>} label="Platform revenue" value={money(analytics.total_revenue_ngn||0)}/></div>
 <div className="grid md:grid-cols-3 gap-2.5"><Quick to="/admin/control" title="People & applications" text="Manage writers, editors, applications and account access." icon={<Users/>}/><Quick to="/admin/control" title="Withdrawals & disputes" text="Approve payouts, inspect bank destinations and resolve disputes." icon={<WalletCards/>}/><Quick to="/admin/control" title="Analytics" text="Revenue, population, trends and operational performance." icon={<TrendingUp/>}/></div>
 <div className="rounded-2xl border border-border bg-background p-4"><div className="flex items-center justify-between gap-3 mb-3"><div><h2 className="font-semibold">Platform pulse</h2><p className="text-xs text-muted-foreground">Revenue, project activity and workflow health.</p></div><Link to="/admin/control" className="text-xs text-primary font-semibold">Open Admin Center <ArrowRight className="inline w-3 h-3"/></Link></div><DashboardAnalytics role="admin" projects={projects} payments={payments}/></div>
 </div>;}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <div className="rounded-2xl border border-border bg-background px-3 py-3"><span className="text-primary">{React.cloneElement(icon as React.ReactElement,{className:'w-4 h-4'})}</span><p className="text-[10px] uppercase tracking-wider text-muted-foreground mt-2">{label}</p><p className="text-lg font-bold truncate">{value}</p></div>}
function Quick({to,title,text,icon}:{to:string;title:string;text:string;icon:React.ReactNode}){return <Link to={to} className="rounded-2xl border border-border bg-background p-4 hover:border-primary/30 hover:bg-primary/5 transition group"><span className="text-primary">{icon}</span><div className="flex items-center justify-between gap-3 mt-3"><div><h3 className="font-semibold text-sm">{title}</h3><p className="text-xs text-muted-foreground mt-1">{text}</p></div><ArrowRight className="w-4 h-4 text-muted-foreground group-hover:text-primary"/></div></Link>}
