import React,{useEffect,useState} from 'react';
import {ShieldAlert,Users,DollarSign,FileText,UserCheck,RefreshCw,Wallet as WalletIcon,UserCog,AlertTriangle,CheckCircle2} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import DashboardAnalytics from '../components/DashboardAnalytics';
import RoleOperationsOverview from '../components/RoleOperationsOverview';
export default function AdminDashboard(){
  const {user,userData}=useAuth();
  const [projects,setProjects]=useState<any[]>([]); const [disputes,setDisputes]=useState<any[]>([]); const [stats,setStats]=useState<any>(null); const [alerts,setAlerts]=useState<any[]>([]); const [writers,setWriters]=useState<any[]>([]); const [editors,setEditors]=useState<any[]>([]); const [writerApps,setWriterApps]=useState<any[]>([]); const [editorApps,setEditorApps]=useState<any[]>([]); const [payments,setPayments]=useState<any[]>([]); const [withdrawals,setWithdrawals]=useState<any[]>([]); const [selectedWriter,setSelectedWriter]=useState<Record<string,string>>({}); const [selectedEditor,setSelectedEditor]=useState<Record<string,string>>({}); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
  const load=async()=>{setLoading(true);await supabase.rpc('prepare_project_monitoring');const [p,w,e,wa,ea,pay,wd,st,al,ds]=await Promise.all([supabase.from('projects').select('*').order('created_at',{ascending:false}),supabase.from('public_profiles').select('*').eq('verified',true).order('ranking_score',{ascending:false}).order('rating',{ascending:false}),supabase.from('profiles').select('id,full_name,username,role,account_status').eq('role','editor').eq('account_status','approved').order('full_name'),supabase.from('writer_applications').select('*').eq('status','pending').order('created_at',{ascending:false}),supabase.from('editor_applications').select('*').eq('status','pending').order('created_at',{ascending:false}),supabase.from('payments').select('*').order('created_at',{ascending:false}).limit(100),supabase.from('withdrawals').select('*').eq('status','pending').order('created_at',{ascending:false}),supabase.rpc('finalyzed_admin_stats'),supabase.from('service_alerts').select('*').is('resolved_at',null).order('created_at',{ascending:false}).limit(20),supabase.from('project_disputes').select('*').eq('status','open').order('created_at',{ascending:false})]);setProjects(p.data||[]);setWriters(w.data||[]);setEditors(e.data||[]);setStats(st.data||null);setAlerts(al.data||[]);setWriterApps(wa.data||[]);setEditorApps(ea.data||[]);setPayments(pay.data||[]);setWithdrawals(wd.data||[]);setDisputes(ds.data||[]);setLoading(false)};
  useEffect(()=>{if(user&&userData?.role==='admin')void load()},[user,userData]);
  if(userData?.role!=='admin')return <div className="p-8 text-center text-red-500">Administrator access required.</div>;
  if(loading)return <div className="p-8 text-center text-muted-foreground">Loading admin portal…</div>;
  const active=projects.filter(p=>!['completed','cancelled'].includes(p.status)); const revenue=payments.filter(p=>p.status==='completed').reduce((s,p)=>s+Number(p.amount_ngn||0),0); const pendingAssignment=projects.filter(p=>p.status==='paid'); const pendingEditor=projects.filter(p=>p.status==='submitted_for_review');
  const decide=async(id:string,role:'writer'|'editor',decision:'approved'|'rejected')=>{setBusy(true);setMsg('');const {error}=await supabase.rpc('admin_decide_application',{p_application_id:id,p_role:role,p_decision:decision});setMsg(error?error.message:'Application updated.');setBusy(false);if(!error)await load()};
  const assignWriter=async(project:any)=>{const writer=selectedWriter[project.id];if(!writer)return;setBusy(true);setMsg('');const deadline=new Date(Date.now()+5*86400000).toISOString();const {error}=await supabase.rpc('assign_writer',{p_project_id:project.id,p_writer_id:writer,p_deadline_at:deadline});setMsg(error?error.message:'Writer assigned with a 5-day deadline.');setBusy(false);if(!error)await load()};
  const assignEditor=async(project:any)=>{const editor=selectedEditor[project.id];if(!editor)return;setBusy(true);setMsg('');const {error}=await supabase.rpc('assign_editor',{p_project_id:project.id,p_editor_id:editor});setMsg(error?error.message:'Editor assigned to the QA queue.');setBusy(false);if(!error)await load()};
  const processWithdrawal=async(id:string)=>{if(!window.confirm('Initiate this withdrawal through Paystack? Confirm the recipient and amount first.'))return;setBusy(true);setMsg('Initiating Paystack transfer…');try{const session=(await supabase.auth.getSession()).data.session;if(!session)throw new Error('Session expired.');const res=await fetch('/.netlify/functions/paystack-process-withdrawal',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json'},body:JSON.stringify({withdrawal_id:id})});const data=await res.json().catch(()=>({}));if(!res.ok)throw new Error(data.error||'Paystack transfer failed.');setMsg('Paystack transfer initiated successfully.');}catch(e){setMsg(e instanceof Error?e.message:'Paystack transfer failed.')}finally{setBusy(false);await load()}};
  const rejectWithdrawal=async(id:string)=>{const reason=window.prompt('Reason for rejecting this withdrawal:')||'Rejected by administrator';setBusy(true);const {error}=await supabase.rpc('admin_reject_withdrawal',{p_withdrawal_id:id,p_reason:reason});setMsg(error?error.message:'Withdrawal rejected and funds returned.');setBusy(false);if(!error)await load()};
  const resolveDispute=async(projectId:string,resolution:'release_to_writer'|'refund_student'|'split',refundPct=50)=>{const note=window.prompt('Resolution note (optional):')||'';setBusy(true);const {error}=await supabase.rpc('admin_resolve_dispute',{p_project_id:projectId,p_resolution:resolution,p_refund_pct:refundPct,p_note:note||null});setMsg(error?error.message:'Dispute resolved.');setBusy(false);if(!error)await load()};
  return <div className="w-full max-w-7xl mx-auto px-4 py-8 space-y-7"><header className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><span className="mono-label text-red-500 flex items-center gap-2"><ShieldAlert className="w-4 h-4"/>Super Admin Portal</span><h1 className="text-3xl font-light mt-2">FINALYZED <b>OPERATIONS</b></h1><p className="text-sm text-muted-foreground mt-2">Users, managers, writers, projects, revenue, assignments and quality control.</p></div><button onClick={()=>void load()} className="btn-secondary p-3" aria-label="Refresh"><RefreshCw className={`w-4 h-4 ${loading?'animate-spin':''}`}/></button></header>
    {msg&&<div className="p-4 rounded-xl bg-primary/5 border border-primary/20 text-sm">{msg}</div>}{alerts.length>0&&<div className="bento-card p-5 border-amber-500/30 bg-amber-500/5"><div className="flex items-center gap-2 font-bold mb-3"><AlertTriangle className="w-5 h-5 text-amber-500"/>Service warnings</div>{alerts.map(a=><p key={a.id} className="text-sm py-2 border-t border-border/50">{a.message}</p>)}</div>}
    <div className="grid grid-cols-2 lg:grid-cols-5 gap-4"><Metric icon={<Users/>} label="Students" value={String(stats?.students||0)}/><Metric icon={<UserCog/>} label="Project Managers" value={String(stats?.managers||0)}/><Metric icon={<UserCheck/>} label="Finalyzed Writers" value={String(stats?.writers||0)}/><Metric icon={<FileText/>} label="Active projects" value={String(active.length)}/><Metric icon={<DollarSign/>} label="Verified revenue" value={'₦'+Number(stats?.total_revenue_ngn||revenue).toLocaleString('en-NG')}/></div>
    <section className="bento-card p-6"><div className="flex items-center gap-2 mb-5"><Users className="w-5 h-5 text-primary"/><div><h2 className="font-bold text-lg">User vs Project Manager population</h2><p className="text-sm text-muted-foreground">Cross-check the current platform population at a glance.</p></div></div><div className="grid md:grid-cols-3 gap-5">{[['Students',stats?.students||0],['Finalyzed Writers',stats?.writers||0],['Project Managers',stats?.managers||0]].map(([label,value]:any)=>{const total=Math.max(1,(stats?.students||0)+(stats?.writers||0)+(stats?.managers||0));return <div key={label}><div className="flex justify-between text-sm mb-2"><b>{label}</b><span>{value} · {Math.round(value/total*100)}%</span></div><div className="h-3 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary rounded-full" style={{width:(value/total*100)+'%'}}/></div></div>})}</div></section><RoleOperationsOverview role="admin" userId={user.id}/><DashboardAnalytics role="admin" projects={projects} payments={payments}/>
    <section className="bento-card p-6"><h2 className="font-bold text-lg mb-4 flex items-center gap-2"><UserCog className="w-5 h-5 text-primary"/>Project Managers on board</h2>{editors.length===0?<p className="text-sm text-muted-foreground">No approved Project Managers yet.</p>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-3">{editors.map(e=><div key={e.id} className="border border-border rounded-xl p-4 flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-primary/10 flex items-center justify-center text-primary font-bold">{(e.full_name||'M').charAt(0)}</div><div className="min-w-0"><p className="font-semibold truncate">{e.username?'@'+e.username:e.full_name||'Project Manager'}</p><p className="text-xs text-muted-foreground">{e.full_name||'—'} · approved</p></div><CheckCircle2 className="w-4 h-4 text-primary ml-auto"/></div>)}</div>}</section><section className="grid lg:grid-cols-2 gap-6"><ApplicationCard title="Writer Applications" items={writerApps} role="writer" busy={busy} decide={decide}/><ApplicationCard title="Editor Applications" items={editorApps} role="editor" busy={busy} decide={decide}/></section>
    <section className="bento-card p-6 border-amber-500/30"><h2 className="font-bold text-lg mb-2 flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-amber-500"/>Open Disputes</h2><p className="text-sm text-muted-foreground mb-5">Manual administrator resolution for projects where the student has exhausted the included revision allowance.</p>{disputes.length===0?<p className="text-sm text-muted-foreground">No open disputes.</p>:disputes.map(d=>{const p=projects.find(x=>x.id===d.project_id);return <div key={d.id} className="border-t border-border py-5"><div className="flex flex-col lg:flex-row lg:items-start justify-between gap-4"><div className="min-w-0"><p className="font-semibold">{p?.title||'Project dispute'}</p><p className="text-xs text-muted-foreground mt-1">Opened {new Date(d.created_at).toLocaleString('en-NG')}</p><p className="text-sm mt-3 leading-relaxed">{d.reason}</p></div><div className="grid sm:grid-cols-3 gap-2 shrink-0"><button disabled={busy} onClick={()=>void resolveDispute(d.project_id,'release_to_writer',0)} className="btn-primary px-3 py-2 text-xs">Release to Writer</button><button disabled={busy} onClick={()=>void resolveDispute(d.project_id,'refund_student',100)} className="px-3 py-2 rounded-lg border border-primary/30 text-primary text-xs">Refund Student</button><button disabled={busy} onClick={()=>{const raw=window.prompt('Refund percentage (0–100):','50');const pct=Number(raw);if(Number.isInteger(pct)&&pct>=0&&pct<=100)void resolveDispute(d.project_id,'split',pct)}} className="px-3 py-2 rounded-lg border border-amber-500/30 text-amber-500 text-xs">Split</button></div></div></div>})}</section>
    <section className="bento-card p-6"><h2 className="font-bold text-lg mb-4">Paid Projects Awaiting Writer Assignment</h2>{pendingAssignment.length===0?<p className="text-sm text-muted-foreground">No paid projects awaiting assignment.</p>:pendingAssignment.map(p=><div key={p.id} className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 py-4 border-b border-border last:border-0"><div className="min-w-0"><p className="font-semibold truncate">{p.title}</p><p className="text-sm text-muted-foreground">{p.plan} · ₦{Number(p.price_ngn).toLocaleString('en-NG')}</p></div><div className="flex gap-2 w-full lg:w-auto"><select disabled={busy||writers.length===0} onChange={e=>setSelectedWriter(s=>({...s,[p.id]:e.target.value}))} value={selectedWriter[p.id]||""} className="form-input text-sm flex-1 lg:w-72"><option value="">Select verified writer</option>{writers.map(w=><option key={w.id} value={w.id}>{w.display_name} · {Number(w.ranking_score||0).toFixed(1)} rank</option>)}</select><button disabled={busy||!selectedWriter[p.id]} onClick={()=>assignWriter(p)} className="btn-primary px-4 py-2 text-sm">Assign</button></div></div>)}</section>
    <section className="bento-card p-6"><h2 className="font-bold text-lg mb-4">Submissions Awaiting Editor Assignment</h2>{pendingEditor.length===0?<p className="text-sm text-muted-foreground">No submissions awaiting editor assignment.</p>:pendingEditor.map(p=><div key={p.id} className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 py-4 border-b border-border last:border-0"><div><p className="font-semibold">{p.title}</p><p className="text-sm text-muted-foreground">{p.plan} · writer {p.writer_id?.slice(0,8)||'—'}</p></div><div className="flex gap-2 w-full lg:w-auto"><select disabled={busy||editors.length===0} onChange={e=>setSelectedEditor(s=>({...s,[p.id]:e.target.value}))} value={selectedEditor[p.id]||""} className="form-input text-sm flex-1 lg:w-72"><option value="">Select approved editor</option>{editors.map(e=><option key={e.id} value={e.id}>{e.full_name||e.id.slice(0,8)}</option>)}</select><button disabled={busy||!selectedEditor[p.id]} onClick={()=>assignEditor(p)} className="btn-primary px-4 py-2 text-sm">Assign Editor</button></div></div>)}</section>
    <section className="bento-card p-6"><h2 className="font-bold text-lg mb-4 flex items-center gap-2"><WalletIcon className="w-5 h-5 text-primary"/>Pending Withdrawals</h2>{withdrawals.length===0?<p className="text-sm text-muted-foreground">No pending withdrawals.</p>:withdrawals.map(w=><div key={w.id} className="flex flex-col lg:flex-row lg:items-center justify-between gap-3 py-4 border-b border-border last:border-0"><div><p className="font-semibold">₦{Number(w.amount_ngn).toLocaleString('en-NG')} + ₦{Number(w.transaction_fee_ngn).toLocaleString('en-NG')} fee</p><p className="text-sm text-muted-foreground">{w.bank_name} · {w.account_name} · ****{w.account_number_last4||'—'}</p></div><div className="flex gap-2"><button disabled={busy} onClick={()=>processWithdrawal(w.id)} className="btn-primary px-4 py-2 text-sm">Pay via Paystack</button><button disabled={busy} onClick={()=>rejectWithdrawal(w.id)} className="px-4 py-2 rounded-lg border border-red-500/30 text-red-500 text-sm">Reject</button></div></div>)}</section>
  </div>;
}
function ApplicationCard({title,items,role,busy,decide}:{title:string;items:any[];role:'writer'|'editor';busy:boolean;decide:(id:string,role:'writer'|'editor',decision:'approved'|'rejected')=>Promise<void>}){return <div className="bento-card p-6"><h2 className="font-bold text-lg mb-4">{title}</h2>{items.length===0?<p className="text-sm text-muted-foreground">No pending applications.</p>:items.map(a=><div key={a.id} className="border-b border-border py-4 last:border-0"><p className="font-semibold">{a.user_id}</p><p className="text-sm text-muted-foreground line-clamp-2">{a.bio}</p><div className="flex gap-2 mt-3"><button disabled={busy} onClick={()=>decide(a.id,role,'approved')} className="btn-primary px-4 py-2 text-sm">Approve</button><button disabled={busy} onClick={()=>decide(a.id,role,'rejected')} className="px-4 py-2 rounded-lg border border-red-500/30 text-red-500 text-sm">Reject</button></div></div>)}</div>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="bento-card p-6"><span className="text-primary">{icon}</span><p className="text-xs uppercase tracking-wider text-muted-foreground mt-3">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
