import React,{useEffect,useMemo,useState} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {ArrowRight,CheckCircle,Clock,Search,ShieldCheck,Star,User,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {useAuth} from '../contexts/AuthContext';

type Editor={id:string;name:string;bio:string;specialties:string[];verified:boolean;rating:number;reviews:number;completed:number;accuracy:number;days:number;basic:number;standard:number;premium:number;avatar?:string};

export default function EditorMarketplace(){
 const {user,userData}=useAuth(); const [params]=useSearchParams(); const projectId=params.get('project')||''; const [rows,setRows]=useState<Editor[]>([]); const [q,setQ]=useState(''); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(''); const [message,setMessage]=useState('');
 useEffect(()=>{let live=true;(async()=>{const {data,error}=await supabase.from('public_profiles').select('*').eq('role','editor').eq('verified',true).order('ranking_score',{ascending:false});if(error){setMessage(error.message);setLoading(false);return}const ids=(data||[]).map((x:any)=>x.id);let rates:any[]=[];if(ids.length){const r=await supabase.from('editor_rates').select('*').in('editor_id',ids);rates=r.data||[]}if(live){setRows((data||[]).map((x:any)=>{const r=rates.find(y=>y.editor_id===x.id);return{id:x.id,name:x.display_name||'Finalyzed Editor',bio:x.bio||'Editorial QA specialist.',specialties:x.specialties||[],verified:!!x.verified,rating:Number(x.rating||0),reviews:Number(x.review_count||0),completed:Number(x.completed_projects||0),accuracy:Number(x.accuracy_score||0),days:Number(x.average_delivery_days||0),basic:Number(r?.basic_points||100),standard:Number(r?.standard_points||100),premium:Number(r?.premium_points||100),avatar:x.avatar_url}}));setLoading(false)}})();return()=>{live=false}},[]);
 const filtered=useMemo(()=>{const s=q.trim().toLowerCase();return rows.filter(e=>!s||e.name.toLowerCase().includes(s)||e.bio.toLowerCase().includes(s)||e.specialties.some(x=>x.toLowerCase().includes(s)))},[rows,q]);
 const choose=async(id:string)=>{if(!user||userData?.role!=='writer'||!projectId){setMessage('Open the editor marketplace from an active project to assign an editor.');return}setBusy(id);setMessage('');const {error}=await supabase.rpc('writer_assign_editor',{p_project_id:projectId,p_editor_id:id});setBusy('');if(error){setMessage(error.message);return}setMessage('Editor selected. They have received the project review request.');};
 return <div className="w-full max-w-7xl mx-auto px-4 py-6 md:py-9 space-y-6">
  <header className="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><span className="mono-label text-primary">Finalyzed Editor Marketplace</span><h1 className="text-2xl md:text-3xl font-bold mt-1">Choose a <b>Project Editor</b></h1><p className="text-sm text-muted-foreground mt-2 max-w-2xl">Compare approved editors by QA history, ratings, turnaround and their review rate before assigning them to this project.</p></div><div className="relative w-full md:w-80"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground"/><input value={q} onChange={e=>setQ(e.target.value)} className="form-input pl-9 py-2.5" placeholder="Search editors or expertise…"/></div></header>
  {message&&<div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-sm">{message}</div>}
  {loading?<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-3">{[1,2,3,4,5].map(i=><div key={i} className="bento-card h-64 animate-pulse p-4"><div className="h-10 w-10 rounded-xl bg-muted"/><div className="h-4 bg-muted rounded mt-4 w-2/3"/><div className="h-3 bg-muted rounded mt-2 w-full"/></div>)}</div>
  :filtered.length===0?<div className="bento-card p-10 text-center"><User className="w-9 h-9 mx-auto text-primary/40"/><h2 className="font-bold mt-3">No approved editors found</h2><p className="text-sm text-muted-foreground mt-1">Try another search or check back after editors are approved.</p></div>
  :<div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-5 gap-3">{filtered.map(e=><article key={e.id} className="bento-card p-3 flex flex-col min-w-0 hover:border-primary/40 transition-colors"><Link to={'/editors/'+e.id+(projectId?'?project='+encodeURIComponent(projectId):'')} className="block"><div className="flex items-start justify-between gap-2"><div className="w-10 h-10 rounded-xl overflow-hidden bg-primary/10 border border-border flex items-center justify-center">{e.avatar?<img src={e.avatar} alt="" className="w-full h-full object-cover"/>:<User className="w-4 h-4 text-primary"/>}</div><span className="inline-flex items-center gap-1 text-[8px] font-bold uppercase text-primary bg-primary/10 border border-primary/20 rounded-full px-1.5 py-1"><ShieldCheck className="w-3 h-3"/>Verified</span></div><h2 className="text-xs font-bold mt-3 truncate">{e.name}</h2><p className="text-[10px] text-muted-foreground line-clamp-2 mt-1 min-h-7">{e.bio}</p><div className="flex flex-wrap gap-1 mt-2">{e.specialties.slice(0,2).map(s=><span key={s} className="text-[8px] px-1.5 py-0.5 rounded bg-muted border border-border">{s}</span>)}</div><div className="grid grid-cols-2 gap-2 mt-3 pt-3 border-t border-border"><Mini icon={<Star/>} value={e.rating.toFixed(1)} label={e.reviews+' reviews'}/><Mini icon={<CheckCircle/>} value={String(e.completed)} label="completed"/><Mini icon={<Clock/>} value={e.days?e.days+'d':'—'} label="turnaround"/><Mini icon={<WalletCards/>} value={String(e.basic)} label="base points"/></div></Link>{projectId&&<button disabled={!!busy} onClick={()=>void choose(e.id)} className="btn-primary w-full py-2 mt-3 text-[10px]">{busy===e.id?'Requesting…':'Choose editor'}</button>}</article>)}</div>}
 </div>;
}
function Mini({icon,value,label}:{icon:React.ReactNode;value:string;label:string}){return <div className="min-w-0"><div className="flex items-center gap-1 font-bold text-xs text-foreground">{React.cloneElement(icon as React.ReactElement,{className:'w-3 h-3 text-primary'})}{value}</div><div className="text-[8px] text-muted-foreground truncate">{label}</div></div>}
