import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {ShieldCheck,Clock,CheckCircle,RefreshCw,ChevronRight,FolderKanban} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import DashboardAnalytics from '../components/DashboardAnalytics';
const label=(s:string)=>String(s||'').replace(/_/g,' ');
export default function EditorDashboard(){
 const {user,userData}=useAuth();const [projects,setProjects]=useState<any[]>([]);const [revisions,setRevisions]=useState<any[]>([]);const [reviews,setReviews]=useState<any[]>([]);const [wallet,setWallet]=useState<any>(null);const [writerNames,setWriterNames]=useState<Record<string,string>>({});const [filter,setFilter]=useState('current');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user)return;let live=true;(async()=>{const [p,q,w]=await Promise.all([supabase.from('projects').select('*').eq('editor_id',user.id).order('created_at',{ascending:false}),supabase.from('qa_reviews').select('*').eq('editor_id',user.id).order('created_at',{ascending:false}),supabase.from('wallets').select('*').eq('user_id',user.id).maybeSingle()]);const rows=p.data||[];let rev:any[]=[];if(rows.length){const rr=await supabase.from('project_revisions').select('*').in('project_id',rows.map(x=>x.id)).order('created_at',{ascending:false});rev=rr.data||[]}if(live){const ids=[...new Set(rows.map(x=>x.writer_id).filter(Boolean))];let names:Record<string,string>={};if(ids.length){const pr=await supabase.from('profiles').select('id,full_name').in('id',ids);(pr.data||[]).forEach(x=>{names[x.id]=x.full_name||'Writer'})}setProjects(rows);setReviews(q.data||[]);setRevisions(rev);setWallet(w.data||null);setWriterNames(names);setLoading(false)}})();return()=>{live=false}},[user]);
 const pendingQA=projects.filter(p=>p.status==='submitted_for_review');const pendingRevisions=revisions.filter(r=>['requested','accepted','pending'].includes(r.status));const shown=useMemo(()=>filter==='current'?projects.filter(p=>!['completed','cancelled'].includes(p.status)):filter==='qa'?pendingQA:filter==='revisions'?pendingRevisions.map(r=>projects.find(p=>p.id===r.project_id)).filter(Boolean):projects.filter(p=>p.status===filter),[projects,revisions,filter]);
 if(loading)return <div className="p-8 text-center text-muted-foreground">Loading Project Manager portal…</div>;
 return <div className="w-full px-4 sm:px-6 lg:px-8 py-8 space-y-6"><header><span className="mono-label text-primary">Project Manager / Quality Assurance</span><h1 className="text-3xl font-light mt-2">Welcome, <b>{userData?.name?.split(' ')[0]||'Editor'}</b></h1><p className="text-sm text-muted-foreground mt-2">See what needs review, which writers need corrections, and every project under your supervision.</p></header>
 <div className="grid grid-cols-2 sm:grid-cols-2 lg:grid-cols-4 gap-3 md:gap-4"><Metric icon={<ShieldCheck/>} label="Pending QA" value={String(pendingQA.length)}/><Metric icon={<RefreshCw/>} label="Pending revisions" value={String(pendingRevisions.length)}/><Metric icon={<CheckCircle/>} label="Approved QA" value={String(reviews.filter(r=>r.decision==='approved').length)}/><Metric icon={<Clock/>} label="Points" value={Number(wallet?.points_balance||0).toLocaleString()}/></div>
 <DashboardAnalytics role="editor" projects={projects} revisions={revisions} reviews={reviews}/>
 <section className="bento-card p-6 border-primary/20"><div className="flex items-center gap-3 mb-4"><RefreshCw className="w-5 h-5 text-primary"/><div><h2 className="text-xl font-bold">Revisions</h2><p className="text-sm text-muted-foreground">Pending revision work, grouped by the project/writer assignment.</p></div></div>{pendingRevisions.length===0?<p className="text-muted-foreground py-6 text-center">No revision requests waiting for QA.</p>:<div className="divide-y divide-border">{pendingRevisions.map(r=>{const p=projects.find(x=>x.id===r.project_id);return <Link key={r.id} to={'/workspace/'+r.project_id} className="flex items-center justify-between gap-3 py-4"><div><p className="font-semibold">{p?.title||'Project'}</p><p className="text-xs text-muted-foreground mt-1">Writer: {writerNames[p?.writer_id]||'Assigned writer'} · {r.request_text||'Revision requested'}</p></div><span className="text-xs font-bold uppercase text-primary">{label(r.status)}</span></Link>})}</div>}</section>
 <section className="bento-card p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5"><div className="flex items-center gap-3"><FolderKanban className="w-5 h-5 text-primary"/><h2 className="text-xl font-bold">Projects</h2></div><div className="flex flex-wrap gap-2">{['current','qa','revisions','completed'].map(f=><button key={f} onClick={()=>setFilter(f)} className={'px-3 py-1.5 rounded-full text-xs font-semibold border '+(filter===f?'bg-primary text-primary-foreground border-primary':'border-border text-muted-foreground')}>{f[0].toUpperCase()+f.slice(1)}</button>)}</div></div>{shown.length===0?<p className="text-muted-foreground py-8 text-center">Nothing to show here.</p>:<div className="divide-y divide-border">{shown.map((p:any,i:number)=><Link key={p.id||i} to={'/workspace/'+p.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 py-5 px-2 hover:bg-muted/30 rounded-lg"><div><h3 className="font-semibold">{p.title}</h3><p className="text-sm text-muted-foreground mt-1">{p.plan} · {p.writer_id?'Writer assigned':'Awaiting writer'}</p></div><div className="flex items-center gap-2"><span className="text-xs uppercase font-bold text-primary">{label(p.status)}</span><ChevronRight className="w-4 h-4"/></div></Link>)}</div>}</section>
 </div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="bento-card p-4 md:p-6"><div className="w-5 h-5 text-primary">{icon}</div><p className="text-xs uppercase tracking-wider text-muted-foreground mt-3">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
