import React,{useEffect,useState} from 'react';
import {Link,useSearchParams,useParams} from 'react-router-dom';
import {ArrowLeft,CheckCircle,Clock,ShieldCheck,Star,User,WalletCards} from 'lucide-react';
import {supabase} from '../lib/supabase';
import {useAuth} from '../contexts/AuthContext';

export default function EditorProfile(){
 const {id}=useParams(); const [params]=useSearchParams(); const projectId=params.get('project')||''; const {user,userData}=useAuth(); const [editor,setEditor]=useState<any>(null); const [rate,setRate]=useState<any>(null); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{if(!id)return;let live=true;(async()=>{const [{data:p},{data:r}]=await Promise.all([supabase.from('public_profiles').select('*').eq('id',id).eq('role','editor').maybeSingle(),supabase.from('editor_rates').select('*').eq('editor_id',id).maybeSingle()]);if(live){setEditor(p);setRate(r);setLoading(false)}})();return()=>{live=false}},[id]);
 const choose=async()=>{if(!projectId||userData?.role!=='writer'){setMessage('This editor can only be assigned from an active writer project.');return}setBusy(true);const {error}=await supabase.rpc('writer_assign_editor',{p_project_id:projectId,p_editor_id:id});setBusy(false);setMessage(error?error.message:'Editor request sent. They have been notified and will appear on the project once accepted.');};
 if(loading)return <div className="p-8 text-center text-muted-foreground">Loading editor profile…</div>;
 if(!editor)return <div className="p-8 text-center"><h2 className="font-bold text-xl">Editor not found</h2><Link to="/editors" className="text-primary inline-block mt-3">Return to marketplace</Link></div>;
 return <div className="w-full max-w-5xl mx-auto px-4 py-7 space-y-5"><Link to={'/editors'+(projectId?'?project='+encodeURIComponent(projectId):'')} className="inline-flex items-center gap-2 text-sm text-muted-foreground"><ArrowLeft className="w-4 h-4"/>Back to editor marketplace</Link>
 <div className="grid lg:grid-cols-[1.5fr_.7fr] gap-5"><main className="bento-card p-6 md:p-8"><div className="flex flex-col sm:flex-row gap-5"><div className="w-24 h-24 rounded-2xl overflow-hidden bg-primary/10 border border-border flex items-center justify-center shrink-0">{editor.avatar_url?<img src={editor.avatar_url} alt={editor.display_name} className="w-full h-full object-cover"/>:<User className="text-primary"/>}</div><div className="min-w-0"><div className="flex items-center gap-2 flex-wrap"><h1 className="text-2xl font-bold">{editor.display_name}</h1><span className="text-[9px] inline-flex items-center gap-1 rounded-full bg-primary/10 border border-primary/20 px-2 py-1 text-primary font-bold uppercase"><ShieldCheck className="w-3 h-3"/>Verified editor</span></div><div className="flex items-center gap-1 mt-2 text-sm"><Star className="w-4 h-4 text-primary fill-current"/><b>{Number(editor.rating||0).toFixed(1)}</b><span className="text-muted-foreground">({editor.review_count||0} reviews)</span></div><p className="text-sm text-muted-foreground mt-4 leading-relaxed">{editor.bio||'Finalyzed editorial QA specialist.'}</p></div></div><div className="flex flex-wrap gap-2 mt-6">{(editor.specialties||[]).map((x:string)=><span key={x} className="px-2.5 py-1 rounded-lg bg-muted border border-border text-xs">{x}</span>)}</div>{message&&<div className="mt-5 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm">{message}</div>}{projectId&&<button disabled={busy} onClick={()=>void choose()} className="btn-primary mt-6 px-5 py-3">{busy?'Sending request…':'Commission this editor'}</button>}</main>
 <aside className="space-y-3"><div className="bento-card p-5 space-y-4"><Metric icon={<CheckCircle/>} label="Completed QA reviews" value={editor.completed_projects||0}/><Metric icon={<Clock/>} label="Average turnaround" value={(editor.average_delivery_days||0)+' days'}/><Metric icon={<ShieldCheck/>} label="QA accuracy" value={(editor.accuracy_score||0)+'%'}/></div><div className="bento-card p-5"><div className="flex items-center gap-2 font-bold text-sm"><WalletCards className="w-4 h-4 text-primary"/>Review rates</div><p className="text-xs text-muted-foreground mt-1">Base editor rate is 100 points.</p><div className="grid grid-cols-3 gap-2 mt-4">{[['Basic',rate?.basic_points||100],['Standard',rate?.standard_points||100],['Premium',rate?.premium_points||100]].map(([l,v])=><div key={String(l)} className="rounded-xl border border-border p-3 text-center"><div className="text-[9px] uppercase text-muted-foreground">{l}</div><div className="font-bold text-primary mt-1">{String(v)}</div><div className="text-[8px] text-muted-foreground">points</div></div>)}</div></div></aside></div></div>;
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:any}){return <div className="flex items-center gap-3"><span className="text-primary">{icon}</span><div><p className="text-[10px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="font-bold">{value}</p></div></div>}
