import React,{useEffect,useMemo,useState} from 'react';
import {Search,Building2,CheckCircle,AlertCircle,GraduationCap,ShieldCheck,Eye,ArrowRight,Feather,X} from 'lucide-react';
import {Link} from 'react-router-dom';
import {supabase} from '../lib/supabase';
import {useAuth} from '../contexts/AuthContext';

export default function KnowledgeBase(){
 const {userData}=useAuth();
 const [search,setSearch]=useState('');
 const [institutions,setInstitutions]=useState<any[]>([]);
 const [templates,setTemplates]=useState<any[]>([]);
 const [loading,setLoading]=useState(true);
 const [selected,setSelected]=useState<any|null>(null);

 useEffect(()=>{let live=true;(async()=>{const [{data:i},{data:g},{data:t}]=await Promise.all([supabase.from('institutions').select('*').order('name'),supabase.from('institution_guidelines').select('*').order('observed_at',{ascending:false}),supabase.from('institution_templates').select('id,name,description,institution_id,specification_schema,specification_defaults,verified,usage_count,is_student_derived,created_at').eq('verified',true).order('created_at',{ascending:false})]);if(!live)return;setInstitutions((i||[]).map((x:any)=>({...x,guidelines:(g||[]).filter((y:any)=>y.institution_id===x.id)})));setTemplates(t||[]);setLoading(false)})();return()=>{live=false}},[]);

 const filteredTemplates=useMemo(()=>templates.filter(t=>{const inst=institutions.find(i=>i.id===t.institution_id);const q=search.toLowerCase();return !q||String(t.name||'').toLowerCase().includes(q)||String(t.description||'').toLowerCase().includes(q)||String(inst?.name||'').toLowerCase().includes(q)}),[templates,institutions,search]);
 const filteredInstitutions=useMemo(()=>institutions.filter(i=>{const q=search.toLowerCase();return !q||String(i.name||'').toLowerCase().includes(q)}),[institutions,search]);

 return <div className="w-full max-w-7xl mx-auto px-4 py-6 md:py-10 space-y-8">
  <header className="text-center"><span className="mono-label text-primary">Finalyzed Knowledge Base</span><h1 className="text-3xl md:text-5xl font-light tracking-tight mt-3">Institutional <b>Knowledge</b></h1><p className="text-muted-foreground max-w-2xl mx-auto mt-3">Reusable project templates and verified institutional requirements, kept separate from each student's private project specification.</p></header>
  <div className="max-w-2xl mx-auto relative"><Search className="absolute left-4 top-4 w-5 h-5 text-muted-foreground"/><input value={search} onChange={e=>setSearch(e.target.value)} className="form-input pl-12 py-4" placeholder="Search templates or institutions…"/></div>

  <section className="space-y-4">
   <div className="flex items-end justify-between gap-3"><div><span className="mono-label text-primary flex items-center gap-2"><Feather className="w-4 h-4"/>Reusable templates</span><h2 className="text-2xl font-bold mt-1">Project Specification Templates</h2></div><span className="text-xs text-muted-foreground">{filteredTemplates.length} available</span></div>
   {loading?<div className="bento-card p-10 text-center text-muted-foreground">Loading knowledge base…</div>:filteredTemplates.length===0?<div className="bento-card p-10 text-center"><GraduationCap className="w-10 h-10 mx-auto opacity-30 mb-3"/><p className="font-semibold">No templates match this search.</p></div>:
   <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{filteredTemplates.map(t=>{const inst=institutions.find(i=>i.id===t.institution_id);return <article key={t.id} className="bento-card p-5 hover:border-primary/30 transition-colors"><div className="flex items-start justify-between gap-3"><div className="w-10 h-10 rounded-xl bg-primary/10 text-primary flex items-center justify-center"><Feather className="w-5 h-5"/></div>{t.verified?<span className="badge-verified text-[10px]">Verified</span>:<span className="text-[10px] px-2 py-1 rounded-full border border-border text-muted-foreground">Community</span>}</div><h3 className="font-bold mt-4">{t.name||'Template'}</h3><p className="text-xs text-muted-foreground mt-1 line-clamp-2">{t.description||'Reusable 13-stage Finalyzed project specification template.'}</p><p className="text-xs text-primary mt-3 flex items-center gap-1"><Building2 className="w-3 h-3"/>{inst?.name||'Institution not specified'}</p><div className="flex gap-2 mt-4"><button onClick={()=>setSelected(t)} className="btn-secondary flex-1 py-2 text-xs flex items-center justify-center gap-1"><Eye className="w-3.5 h-3.5"/>View template</button><Link to={'/start-project?template='+t.id+'&tweak=1'} className="btn-primary flex-1 py-2 text-xs flex items-center justify-center gap-1">Use <ArrowRight className="w-3.5 h-3.5"/></Link></div></article>})}</div>}
  </section>

  <section className="space-y-4"><div><span className="mono-label">Institutional requirements</span><h2 className="text-2xl font-bold mt-1">Institutions</h2></div>{loading?<div className="text-center py-8 text-muted-foreground">Loading…</div>:<div className="grid md:grid-cols-2 xl:grid-cols-3 gap-4">{filteredInstitutions.slice(0,60).map(inst=><div key={inst.id} className="bento-card p-5"><div className="flex items-start gap-3"><Building2 className="w-5 h-5 text-primary mt-0.5"/><div className="min-w-0"><h3 className="font-semibold truncate">{inst.name}</h3><p className="text-xs text-muted-foreground mt-1 capitalize">{inst.institution_type||'university'}{inst.ownership&&inst.ownership!=='other'?' · '+inst.ownership:''}</p></div></div><div className="flex items-center gap-2 mt-4 text-xs">{(inst.guidelines||[]).some((g:any)=>g.verified)?<span className="text-emerald-600 flex items-center gap-1"><CheckCircle className="w-3 h-3"/>Verified requirements</span>:<span className="text-amber-600 flex items-center gap-1"><AlertCircle className="w-3 h-3"/>Community observed</span>}</div></div>)}</div>}</section>

  <div className="rounded-2xl border border-primary/20 bg-primary/5 p-6 flex gap-3"><ShieldCheck className="w-6 h-6 text-primary shrink-0"/><p className="text-sm text-muted-foreground">Student-specific specifications never replace the source template. When a student tweaks a template, their completed specification is stored separately and can later become a new institutional template without changing the original.</p></div>

  {selected&&<TemplatePreview template={selected} institution={institutions.find(i=>i.id===selected.institution_id)} onClose={()=>setSelected(null)}/>}
 </div>;
}

function TemplatePreview({template,institution,onClose}:{template:any;institution:any;onClose:()=>void}){
 const schema=Array.isArray(template.specification_schema)?template.specification_schema:[];const answers=template.specification_defaults||{};
 return <div className="fixed inset-0 z-[100] bg-black/60 backdrop-blur-sm p-3 md:p-6 flex items-center justify-center"><div className="w-full max-w-4xl max-h-[92dvh] overflow-hidden rounded-3xl bg-background border border-border shadow-2xl flex flex-col"><header className="p-5 md:p-6 border-b border-border flex items-start justify-between gap-4"><div><span className="mono-label text-primary">Template preview</span><h2 className="text-xl md:text-2xl font-bold mt-1">{template.name}</h2><p className="text-sm text-muted-foreground mt-1">{institution?.name||'Institution'} · {template.description||'13-stage project specification'}</p></div><button onClick={onClose} className="p-2 rounded-xl hover:bg-muted"><X className="w-5 h-5"/></button></header><div className="flex-1 overflow-y-auto p-5 md:p-6 space-y-5">{schema.map((s:any,i:number)=><section key={s.title} className="rounded-2xl border border-border p-4 md:p-5"><div className="flex gap-3"><span className="w-8 h-8 rounded-lg bg-primary/10 text-primary flex items-center justify-center text-xs font-bold shrink-0">{i+1}</span><div className="min-w-0 flex-1"><h3 className="font-bold">{s.title}</h3><p className="text-xs text-muted-foreground mt-1">{s.description}</p><div className="mt-4 space-y-2">{(s.fields||[]).map((f:any)=><div key={f.key} className="grid grid-cols-1 md:grid-cols-[1fr_1.2fr] gap-1 border-t border-border/60 pt-2 text-sm"><span className="font-medium">{f.label}</span><span className="text-muted-foreground">{formatAnswer(answers[f.key])}</span></div>)}</div></div></div></section>)}</div><footer className="p-4 md:p-5 border-t border-border flex gap-3"><button onClick={onClose} className="btn-secondary flex-1 py-3">Close</button><Link to={'/start-project?template='+template.id+'&tweak=1'} className="btn-primary flex-1 py-3 text-center">Use this template</Link></footer></div></div>
}
function formatAnswer(v:any){if(Array.isArray(v))return v.length?v.join(', '):'—';if(typeof v==='boolean')return v?'Yes':'No';return String(v??'—')||'—';}
