import React, { useEffect, useMemo, useState } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { AlertCircle, Check, ChevronLeft, ChevronRight, Save, ShieldCheck } from 'lucide-react';
import { Navigate, useNavigate, useSearchParams } from 'react-router-dom';
import { useAuth } from '../contexts/AuthContext';
import { loadProjectSpecification, saveProjectSpecification, validateSpecification } from '../lib/projectSpecifications';
import { supabase } from '../lib/supabase';
import { TemplateStep } from '../components/ProjectTemplateManager';
import InstitutionPicker from '../components/InstitutionPicker';

const STEPS = ['Student Info','Project Identity','Institution Requirements','Formatting','Page & Length','Structure','Citation & References','Methodology','Data & Results','Appendices','Presentation','Special Instructions','Confirmation'];
const DEFAULTS: Record<string, any> = { projectType:'', citationStyle:'', fontFamily:'Times New Roman', bodyFontSize:'12', headingFontSize:'12', lineSpacing:'2.0', alignment:'Justified', marginLeft:'1.5', marginRight:'1', marginTop:'1', marginBottom:'1', chapterCount:'5', appendices:[] };

type WizardData={data:Record<string,any>;update:(key:string,value:any)=>void};
function FieldInput({label,k,type='text',placeholder='',className='',data,update}:WizardData&{label:string;k:string;type?:string;placeholder?:string;className?:string}){return <label className="block space-y-2"><span className="text-sm font-semibold">{label}</span><input type={type} value={data[k]??''} placeholder={placeholder} onChange={e=>update(k,e.target.value)} className={`form-input ${className}`} /></label>}
function FieldText({label,k,placeholder='',className='',data,update}:WizardData&{label:string;k:string;placeholder?:string;className?:string}){return <label className="block space-y-2"><span className="text-sm font-semibold">{label}</span><textarea value={data[k]??''} placeholder={placeholder} onChange={e=>update(k,e.target.value)} className={`form-input min-h-[120px] resize-y ${className}`} /></label>}
function FieldSelect({label,k,options,data,update}:WizardData&{label:string;k:string;options:string[]}){return <label className="block space-y-2"><span className="text-sm font-semibold">{label}</span><select value={data[k]??''} onChange={e=>update(k,e.target.value)} className="form-input"><option value="">Select {label}</option>{options.map(o=><option key={o} value={o}>{o}</option>)}</select></label>}
function FieldCheckbox({label,k,data,update}:WizardData&{label:string;k:string}){return <label className="flex items-center gap-3 rounded-xl border border-border p-3 cursor-pointer hover:bg-muted/40"><input type="checkbox" checked={Boolean(data[k])} onChange={e=>update(k,e.target.checked)} className="w-4 h-4"/><span className="text-sm">{label}</span></label>}
function DynamicTemplateStep({step,template,data,update}:{step:number;template:TemplateStep;data:Record<string,any>;update:(key:string,value:any)=>void}){return <><WizardStepTitle n={step+1} title={template.title} text={template.description}/><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{template.fields.map(field=><DynamicField key={field.key} field={field} data={data} update={update}/>)}</div></>}
function DynamicField({field,data,update}:{field:any;data:Record<string,any>;update:(key:string,value:any)=>void}){const value=data[field.key];if(field.key==='institution')return <div><InstitutionPicker value={String(value||'')} onChange={v=>update(field.key,v)} required={Boolean(field.required)}/></div>;if(field.type==='checkbox')return <label className="flex items-center gap-3 rounded-xl border border-border p-4 cursor-pointer hover:bg-muted/40"><input type="checkbox" checked={Boolean(value)} onChange={e=>update(field.key,e.target.checked)} className="w-5 h-5"/><span className="text-sm font-semibold">{field.label}{field.required&&<span className="text-primary"> *</span>}</span></label>;if(field.type==='textarea')return <label className="block space-y-2 md:col-span-2"><span className="text-sm font-semibold">{field.label}{field.required&&<span className="text-primary"> *</span>}</span><textarea value={value??''} placeholder={field.placeholder||''} onChange={e=>update(field.key,e.target.value)} className="form-input min-h-[120px] resize-y"/></label>;if(field.type==='multiselect')return <fieldset className="md:col-span-2 space-y-2"><legend className="text-sm font-semibold">{field.label}{field.required&&<span className="text-primary"> *</span>}</legend><div className="grid sm:grid-cols-2 gap-2">{(field.options||[]).map((o:string)=><label key={o} className="flex items-center gap-3 rounded-xl border border-border p-3 cursor-pointer"><input type="checkbox" checked={Array.isArray(value)&&value.includes(o)} onChange={e=>update(field.key,e.target.checked?[...(Array.isArray(value)?value:[]),o]:(Array.isArray(value)?value:[]).filter((x:string)=>x!==o))} className="w-4 h-4"/><span className="text-sm">{o}</span></label>)}</div></fieldset>;if(field.type==='select')return <label className="block space-y-2"><span className="text-sm font-semibold">{field.label}{field.required&&<span className="text-primary"> *</span>}</span><select value={value??''} onChange={e=>update(field.key,e.target.value)} className="form-input"><option value="">Select {field.label}</option>{(field.options||[]).map((o:string)=><option key={o} value={o}>{o}</option>)}</select></label>;return <label className="block space-y-2"><span className="text-sm font-semibold">{field.label}{field.required&&<span className="text-primary"> *</span>}</span><input type={field.type==='number'?'number':'text'} value={value??''} placeholder={field.placeholder||''} onChange={e=>update(field.key,e.target.value)} className="form-input"/></label>}
function WizardStepTitle({n,title,text}:{n:number;title:string;text:string}){return <div className="mb-6"><div className="text-xs font-bold uppercase tracking-[0.18em] text-primary">Step {n}</div><h2 className="text-2xl font-bold mt-1">{title}</h2><p className="text-muted-foreground mt-2 max-w-2xl">{text}</p></div>}

function exportSpecificationPDF(data:Record<string,any>,steps:TemplateStep[]|null){const escape=(v:any)=>String(v??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'} as any)[c]);const sections=(steps||STEPS.map(title=>({title,description:'',fields:[]} as any))).map((s:any,i:number)=>{const fields=(s.fields||[]);const rows=fields.length?fields.map((f:any)=>`<tr><td><b>${escape(f.label)}</b></td><td>${escape(Array.isArray(data[f.key])?data[f.key].join(', '):data[f.key])}</td></tr>`).join(''):`<tr><td colspan="2">Complete this section using the Finalyzed project specification workflow.</td></tr>`;return `<section><h2>${i+1}. ${escape(s.title)}</h2><table>${rows}</table></section>`}).join('');const w=window.open('','_blank','width=900,height=700');if(!w)return;w.document.write(`<!doctype html><html><head><title>Finalyzed Project Specification</title><style>@page{size:A4;margin:18mm}body{font-family:Arial,sans-serif;color:#17202a;line-height:1.5}h1{font-size:25px}h2{font-size:17px;margin-top:24px}table{width:100%;border-collapse:collapse}td{border:1px solid #ddd;padding:9px;vertical-align:top}td:first-child{width:34%;background:#f5f7f8}@media print{.no-print{display:none}}</style></head><body><button class="no-print" onclick="window.print()">Download / Save as PDF</button><h1>Finalyzed Project Specification</h1><p>Project: <b>${escape(data.projectTitle||'Untitled project')}</b></p>${sections}</body></html>`);w.document.close();setTimeout(()=>w.print(),300)}
export default function ProjectWizardV2() {
  const { user, userData } = useAuth(); const navigate = useNavigate(); const [searchParams] = useSearchParams();
  const [step,setStep] = useState(0); const [data,setData] = useState<Record<string,any>>(DEFAULTS); const [sourceTemplateName,setSourceTemplateName]=useState(''); const [sourceTemplateInstitutionId,setSourceTemplateInstitutionId]=useState<string|null>(null); const [saving,setSaving] = useState(false); const [saved,setSaved] = useState(false); const [confirmed,setConfirmed] = useState(false); const [errors,setErrors] = useState<string[]>([]); const [loaded,setLoaded] = useState(false); const [templateSchema,setTemplateSchema] = useState<TemplateStep[]|null>(null);
  const specialistId = localStorage.getItem('finalyzed_selected_specialist') || '';
  const templateId = searchParams.get('template') || '';
  useEffect(()=>{let cancelled=false;(async()=>{if(!user||!loaded)return;try{if(templateId){const {data:t,error}=await supabase.from('institution_templates').select('id,name,institution_id,specification_schema,specification_defaults').eq('id',templateId).maybeSingle();if(error||!t)throw error||new Error('Template not found.');if(cancelled)return;setTemplateSchema((t.specification_schema||[]) as TemplateStep[]);setSourceTemplateName(t.name||'');setSourceTemplateInstitutionId(t.institution_id||null);setData(p=>({...DEFAULTS,...(t.specification_defaults||{})}));setStep(0);return;}if(data.institution){const inst=await supabase.from('institutions').select('id').ilike('name',String(data.institution)).limit(1).maybeSingle();if(inst.data?.id){const r=await supabase.from('institution_templates').select('id,name,institution_id,specification_schema,specification_defaults').eq('institution_id',inst.data.id).eq('verified',true).order('updated_at',{ascending:false}).limit(1).maybeSingle();if(!cancelled&&r.data){setTemplateSchema((r.data.specification_schema||[]) as TemplateStep[]);setSourceTemplateName(r.data.name||'');setSourceTemplateInstitutionId(r.data.institution_id||null);setData(p=>({...p,...(r.data?.specification_defaults||{})}));}}}}catch(e){console.error('Template load failed',e)}})();return()=>{cancelled=true}},[user,loaded,templateId,data.institution]);

  useEffect(()=>{let cancelled=false;(async()=>{if(!user)return;try{if(templateId){if(!cancelled)setLoaded(true);return;}const remote=await loadProjectSpecification(user.id);if(cancelled)return;if(remote){setData({...DEFAULTS,...remote});}else if(userData?.studentProfile){setData(p=>({...p,fullName:userData.name||'',email:user.email||'',institution:userData.studentProfile.institution||'',faculty:userData.studentProfile.faculty||'',department:userData.studentProfile.department||'',degree:userData.studentProfile.degree||'',matricNumber:userData.studentProfile.matricNumber||'',supervisor:userData.studentProfile.supervisor||'',hod:userData.studentProfile.hod||''}));}}catch(e){console.error(e)}finally{if(!cancelled)setLoaded(true)}})();return()=>{cancelled=true}},[user,userData,templateId]);

  useEffect(()=>{ if(!user||!loaded||confirmed)return; localStorage.setItem('finalyzed_project_draft',JSON.stringify(data)); const timer=window.setTimeout(async()=>{try{setSaving(true);await saveProjectSpecification(user.id,{...data,selectedSpecialistId:specialistId},'DRAFT');setSaved(true);}catch(e){console.error('Draft save failed',e);}finally{setSaving(false);}},1500); return()=>window.clearTimeout(timer);},[data,user,loaded,confirmed,specialistId]);

  const update=(key:string,value:any)=>{setData(p=>({...p,[key]:value}));setErrors([]);};
  const required:Record<number,Array<[string,string]>>={0:[['fullName','Full name'],['matricNumber','Matriculation/registration number'],['institution','Institution'],['department','Department'],['degree','Degree/award']],1:[['projectTitle','Approved project title'],['projectType','Project type']],3:[['fontFamily','Font family'],['lineSpacing','Line spacing']],6:[['citationStyle','Citation style']],7:[['methodology','Methodology/design approach']]};
  const schemaForValidation=templateSchema?.length?templateSchema:FINALYZED_DEFAULT_TEMPLATE;
  const isAnswered=(field:any)=>{const v=data[field.key];if(field.type==='checkbox')return typeof v==='boolean';if(field.type==='multiselect')return Array.isArray(v)&&v.length>0;return String(v??'').trim()!=='';};
  const validateStep=()=>{const fields=schemaForValidation[step]?.fields||[];const missing=fields.filter(isAnswered).length===fields.length?[]:fields.filter((field:any)=>!isAnswered(field)).map((field:any)=>`${field.label} is required.`);setErrors(missing);return !missing.length;};
  const activeSteps=templateSchema?.map(s=>s.title)||STEPS;
  const next=()=>{if(validateStep())setStep(s=>Math.min(activeSteps.length-1,s+1));};
  const confirm=async()=>{if(!user)return;const schema=schemaForValidation;const missing=schema.flatMap((s:any)=>s.fields.filter((f:any)=>!isAnswered(f)).map((f:any)=>`${s.title}: ${f.label} is required.`));if(missing.length){setErrors(missing);setStep(0);return;}if(!confirmed){setErrors(['Please confirm that you reviewed the specification.']);return;}try{setSaving(true);let institutionId=sourceTemplateInstitutionId||data.institutionId||null;if(!institutionId&&data.institution){const inst=await supabase.from('institutions').select('id').ilike('name',String(data.institution)).limit(1).maybeSingle();institutionId=inst.data?.id||null;}const {data:spec,error:specError}=await supabase.from('project_specifications').insert({student_id:user.id,institution_id:institutionId,source_template_id:templateId||null,source_template_name:sourceTemplateName||null,title:data.projectTitle||'Project Specification',specification_schema:schema,answers:{...data,selectedSpecialistId:specialistId},status:'confirmed',is_complete:true,submitted_at:new Date().toISOString()}).select('id').single();if(specError)throw specError;await saveProjectSpecification(user.id,{...data,institutionId,selectedSpecialistId:specialistId,specificationId:spec?.id},'CONFIRMED');localStorage.setItem('finalyzed_project_confirmed',JSON.stringify({...data,institutionId,selectedSpecialistId:specialistId,specificationId:spec?.id}));navigate('/checkout');}catch(e){console.error(e);setErrors(['We could not save your confirmed specification. Please try again.']);}finally{setSaving(false);}};



  const summary=useMemo(()=>[['Title',data.projectTitle],['Institution',data.institution],['Department',data.department],['Project Type',data.projectType],['Target Pages',data.targetPages||data.maxPages],['Citation',data.citationStyle],['Chapters',data.chapterCount],['Specialist',specialistId?'Selected specialist':'To be assigned']], [data,specialistId]);
  const chapterCount=Math.min(8,Math.max(1,Number(data.chapterCount)||5));

  if (!user) return <Navigate to="/login" replace state={{ from: '/start-project' }} />;
  if (userData && userData.role !== 'student') return <Navigate to="/dashboard" replace />;

  const content=()=>{if(templateSchema?.length){const current=templateSchema[step];if(current)return <DynamicTemplateStep step={step} template={current} data={data} update={update}/>;}switch(step){
    case 0:return <><WizardStepTitle n={1} title="Student information" text="Confirm the academic identity used throughout the project."/><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FieldInput data={data} update={update} label="Full name" k="fullName"/><FieldInput data={data} update={update} label="Matriculation / registration number" k="matricNumber"/><FieldInput data={data} update={update} label="Institution" k="institution"/><FieldInput data={data} update={update} label="Faculty / school" k="faculty"/><FieldInput data={data} update={update} label="Department" k="department"/><FieldInput data={data} update={update} label="Degree / award" k="degree"/><FieldInput data={data} update={update} label="Project supervisor" k="supervisor"/><FieldInput data={data} update={update} label="Head of department" k="hod"/><FieldInput data={data} update={update} label="Submission month" k="submissionMonth" placeholder="e.g. August"/><FieldInput data={data} update={update} label="Submission year" k="submissionYear" type="number" placeholder="e.g. 2026"/></div></>;
    case 1:return <><WizardStepTitle n={2} title="Project identity" text="Define exactly what the specialist is being commissioned to deliver."/><div className="space-y-4"><FieldInput data={data} update={update} label="Exact approved project title" k="projectTitle"/><FieldSelect data={data} update={update} label="Project type" k="projectType" options={['Design & Construction','Research Study','Software Development','Case Study','Business Plan','Survey-Based Study','Other']}/><FieldInput data={data} update={update} label="Core subject matter / technology / method" k="subjectArea"/><FieldText data={data} update={update} label="Problem being addressed" k="problemStatement"/><FieldText data={data} update={update} label="Aim and objectives" k="aimObjectives" placeholder="One aim plus measurable objectives."/><FieldText data={data} update={update} label="Target outcome / result" k="expectedOutcome"/><FieldText data={data} update={update} label="Supervisor instructions" k="supervisorInstructions"/><FieldCheckbox data={data} update={update} label="Topic officially approved?" k="topicApproved"/></div></>;
    case 2:return <><WizardStepTitle n={3} title="Institution requirements" text="Capture the real departmental format so writers and editors work from the same specification."/><div className="space-y-4"><FieldSelect data={data} update={update} label="Does your institution have a prescribed project format?" k="hasPrescribedFormat" options={['Yes','No','Unknown']}/>{data.hasPrescribedFormat==='Yes'&&<FieldText data={data} update={update} label="Prescribed format details" k="prescribedFormatDetails"/>}<FieldText data={data} update={update} label="Required preliminary pages" k="preliminaryPages" placeholder="Certification, Dedication, Acknowledgement, Abstract, TOC..."/><FieldText data={data} update={update} label="Required chapter structure / department rules" k="institutionStructure"/><FieldText data={data} update={update} label="Relevant standards / regulatory bodies" k="standardsBodies" placeholder="ISO, CBN, NAFDAC, NCC, engineering standard, etc."/><FieldText data={data} update={update} label="Ethical, safety, data-protection or institutional requirements" k="ethicalRequirements"/></div></>;
    case 3:return <><WizardStepTitle n={4} title="Formatting" text="These settings become part of the writer and editor QA checklist."/><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FieldSelect data={data} update={update} label="Font family" k="fontFamily" options={['Times New Roman','Arial','Calibri','Institution Standard','Other']}/><FieldInput data={data} update={update} label="Body font size (pt)" k="bodyFontSize" type="number"/><FieldInput data={data} update={update} label="Heading font size (pt)" k="headingFontSize" type="number"/><FieldSelect data={data} update={update} label="Line spacing" k="lineSpacing" options={['1.0','1.15','1.5','2.0','Institution Standard']}/><FieldSelect data={data} update={update} label="Body alignment" k="alignment" options={['Justified','Left','Institution Standard']}/><FieldInput data={data} update={update} label="Paragraph indentation" k="paragraphIndentation" placeholder="e.g. 0.5 inch"/><FieldInput data={data} update={update} label="Left margin (inch)" k="marginLeft" type="number"/><FieldInput data={data} update={update} label="Right margin (inch)" k="marginRight" type="number"/><FieldInput data={data} update={update} label="Top margin (inch)" k="marginTop" type="number"/><FieldInput data={data} update={update} label="Bottom margin (inch)" k="marginBottom" type="number"/><FieldSelect data={data} update={update} label="Preliminary numbering" k="preliminaryNumbering" options={['Roman numerals','Arabic numerals','Institution Standard']}/><FieldSelect data={data} update={update} label="Chapter numbering" k="chapterNumbering" options={['Arabic numerals','Institution Standard']}/></div><div className="space-y-4 mt-4"><FieldText data={data} update={update} label="Header / footer rules" k="headerFooterRules"/><FieldText data={data} update={update} label="Table / figure / caption rules" k="tableFigureRules"/></div></>;
    case 4:return <><WizardStepTitle n={5} title="Page & length" text="Requested limits are checked against the plan during checkout."/><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><FieldInput data={data} update={update} label="Minimum pages" k="minPages" type="number"/><FieldInput data={data} update={update} label="Target pages" k="targetPages" type="number"/><FieldInput data={data} update={update} label="Maximum pages" k="maxPages" type="number"/></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4"><FieldCheckbox data={data} update={update} label="Preliminary pages count" k="countPrelim"/><FieldCheckbox data={data} update={update} label="References count" k="countReferences"/><FieldCheckbox data={data} update={update} label="Appendices count" k="countAppendices"/></div><div className="mt-4"><FieldText data={data} update={update} label="Page-budget / length instructions" k="pageBudgetInstructions"/></div></>;
    case 5:return <><WizardStepTitle n={6} title="Structure" text="Define the chapter architecture instead of forcing every department into one template."/><FieldInput data={data} update={update} label="Number of chapters" k="chapterCount" type="number"/><div className="grid grid-cols-1 md:grid-cols-2 gap-4 mt-4">{Array.from({length:chapterCount},(_,i)=><FieldInput data={data} update={update} label={`Chapter ${i+1} title`} k={`chapter${i+1}Title`} placeholder={i===0?'e.g. Introduction':'Required title'}/>)}</div><div className="space-y-4 mt-4"><FieldText data={data} update={update} label="Mandatory sections / subsections" k="mandatorySubsections"/><FieldText data={data} update={update} label="Sections that must be excluded" k="excludedSections"/></div></>;
    case 6:return <><WizardStepTitle n={7} title="Citation & references" text="Citations, source quality and reference consistency are checked by the editor."/><div className="space-y-4"><FieldSelect data={data} update={update} label="Citation style" k="citationStyle" options={['APA','IEEE','Harvard','MLA','Vancouver','Chicago','Other']}/><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FieldInput data={data} update={update} label="Minimum references" k="minReferences" type="number"/><FieldInput data={data} update={update} label="Maximum references" k="maxReferences" type="number"/></div><FieldText data={data} update={update} label="Source requirements" k="sourceRequirements" placeholder="Recent sources, textbooks, journals, exclusions, etc."/><FieldText data={data} update={update} label="Required standards / datasheets / regulatory references" k="requiredReferences"/></div></>;
    case 7:return <><WizardStepTitle n={8} title="Methodology / design" text="Explain how the work should be conducted, built, tested or analysed."/><div className="space-y-4"><FieldText data={data} update={update} label="Methodology / research design / system architecture" k="methodology"/><FieldInput data={data} update={update} label="Required technologies / instruments / tools" k="technologies"/><FieldText data={data} update={update} label="Population, sample, scope or system boundary" k="scope"/><FieldText data={data} update={update} label="Sampling / data collection method" k="dataCollectionMethod"/><FieldText data={data} update={update} label="Analysis / calculation / testing method" k="analysisMethod"/><FieldText data={data} update={update} label="Safety, ethical and regulatory compliance approach" k="complianceApproach"/><FieldText data={data} update={update} label="Design decisions and justification" k="designJustification"/></div></>;
    case 8:return <><WizardStepTitle n={9} title="Data & results" text="Tell us what evidence exists and what the finished work must demonstrate."/><div className="space-y-4"><FieldSelect data={data} update={update} label="Do you already have real project data?" k="hasRealData" options={['Yes','No','Partial']}/><FieldText data={data} update={update} label="Available data / results" k="availableData"/><FieldText data={data} update={update} label="Expected results, tables, charts, diagrams or technical drawings" k="resultRequirements"/><FieldInput data={data} update={update} label="Target performance / measurable outcome" k="targetOutcomeMetric"/><FieldText data={data} update={update} label="Testing / validation requirements" k="testingRequirements"/><div className="p-4 rounded-xl border border-amber-500/20 bg-amber-500/5 text-sm">Finalyzed does not present invented data as genuine research evidence. Any illustrative data must be clearly identified as illustrative.</div></div></>;
    case 9:return <><WizardStepTitle n={10} title="Appendices" text="Select supporting material that should accompany the final deliverable."/><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{['Questionnaire','Interview Questions','Test Log','Bill of Materials','Budget','Code Listing','Technical Drawings','Financial Statements','Reference Tables','Implementation Timeline'].map(item=><label key={item} className="flex items-center gap-3 rounded-xl border border-border p-3 cursor-pointer hover:bg-muted/40"><input type="checkbox" checked={data.appendices?.includes(item)||false} onChange={e=>update('appendices',e.target.checked?[...(data.appendices||[]),item]:(data.appendices||[]).filter((x:string)=>x!==item))}/>{item}</label>)}</div><div className="space-y-4 mt-4"><FieldInput data={data} update={update} label="Other appendices" k="otherAppendices"/><FieldText data={data} update={update} label="Appendix-specific instructions" k="appendixInstructions"/></div></>;
    case 10:return <><WizardStepTitle n={11} title="Presentation" text="Presentation deliverables depend on the selected plan."/><div className="space-y-4"><FieldCheckbox data={data} update={update} label="Project presentation is required" k="presentationRequired"/>{data.presentationRequired&&<><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><FieldInput data={data} update={update} label="Expected slide count" k="slideCount" placeholder="e.g. 15–20"/><FieldSelect data={data} update={update} label="Presentation style" k="presentationStyle" options={['Academic defence','Institution template','Minimal professional','Other']}/></div><FieldText data={data} update={update} label="Defence requirements / likely questions" k="defenceRequirements"/></>}<FieldCheckbox data={data} update={update} label="Simplified presentation guide is required" k="presentationGuideRequired"/><div className="p-4 rounded-xl border border-primary/20 bg-primary/5 text-sm"><strong>Plan reminder:</strong> Standard includes presentation slides. Premium includes slides and the simplified presentation guide.</div></div></>;
    case 11:return <><WizardStepTitle n={12} title="Special instructions" text="Anything important that does not fit elsewhere belongs here."/><div className="space-y-4"><FieldText data={data} update={update} label="Special instructions" k="specialInstructions"/><FieldText data={data} update={update} label="Things the writer must NOT change" k="doNotChange"/><FieldText data={data} update={update} label="Expected communication / delivery instructions" k="deliveryInstructions"/><FieldText data={data} update={update} label="Other notes from supervisor or department" k="otherNotes"/></div></>;
    default:return <><WizardStepTitle n={13} title="Confirm your project specification" text="This version will become the authoritative record attached to your commission."/><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{summary.map(([label,value])=><div key={label} className="rounded-xl border border-border p-4"><div className="text-[11px] uppercase tracking-wider font-bold text-muted-foreground">{label}</div><div className="font-semibold mt-1 break-words">{String(value||'Not specified')}</div></div>)}</div><div className="rounded-xl border border-primary/20 bg-primary/5 p-5 mt-5"><div className="flex items-start gap-3"><ShieldCheck className="w-5 h-5 text-primary mt-0.5"/><div><div className="font-bold">Specification confirmation</div><p className="text-sm text-muted-foreground mt-1">Review all sections before confirming. The writer and editor will use this record as their source of truth.</p></div></div><label className="flex items-start gap-3 mt-5 cursor-pointer"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)} className="w-5 h-5 mt-0.5"/><span className="text-sm font-medium">I have reviewed the project specifications and confirm they accurately represent my requirements.</span></label></div><button onClick={confirm} disabled={!confirmed||saving} className="btn-primary w-full py-4 mt-5 disabled:opacity-50">{saving?'Saving confirmed specification…':'Confirm Specification & Proceed to Checkout'}</button></>;
  }};

  if(user && userData?.role !== 'student') return <div className="max-w-xl mx-auto px-4 py-16 text-center"><AlertCircle className="w-10 h-10 mx-auto text-primary mb-4"/><h1 className="text-2xl font-bold">Project specification is for students</h1><p className="text-muted-foreground mt-2">Finalyzed Writers and Project Managers work from confirmed student specifications; they cannot create or edit one.</p><button onClick={()=>navigate('/dashboard')} className="btn-primary mt-6 px-6 py-3">Return to Dashboard</button></div>;

  if(!user)return <div className="max-w-xl mx-auto px-4 py-16 text-center"><AlertCircle className="w-10 h-10 mx-auto text-primary mb-4"/><h1 className="text-2xl font-bold">Sign in to start your project</h1><p className="text-muted-foreground mt-2">Your specification is saved securely to your Finalyzed account.</p><button onClick={()=>navigate('/login')} className="btn-primary mt-6 px-6 py-3">Sign in</button></div>;
  return <div className="w-full max-w-6xl mx-auto px-4 py-6 md:py-12"><header className="mb-6 md:mb-10 flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><div className="text-xs uppercase tracking-[0.2em] font-bold text-primary">Finalyzed project setup</div><h1 className="text-3xl md:text-4xl font-bold tracking-tight mt-1">Project Specification</h1><p className="text-muted-foreground mt-2">Create one precise specification for the writer and quality editor.</p></div><button type="button" onClick={()=>exportSpecificationPDF(data,templateSchema)} className="px-4 py-2 rounded-xl border border-border hover:bg-muted text-sm font-semibold">Download specification PDF</button><div className="text-sm text-muted-foreground flex items-center gap-2">{saving?<><Save className="w-4 h-4 animate-pulse"/>Saving…</>:saved?<><Check className="w-4 h-4 text-green-500"/>Saved</>:<><Save className="w-4 h-4"/>Autosaved</>}</div></header>{errors.length>0&&<div className="mb-6 rounded-xl border border-red-500/20 bg-red-500/5 p-4"><div className="font-bold flex items-center gap-2"><AlertCircle className="w-4 h-4"/>Please complete the required fields</div><ul className="mt-2 text-sm list-disc pl-5">{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}<div className="grid grid-cols-1 lg:grid-cols-4 gap-8"><aside className="hidden lg:block lg:col-span-1"><nav className="sticky top-24 space-y-1">{activeSteps.map((s,i)=><button key={s} onClick={()=>i<=step&&setStep(i)} className={`w-full text-left px-4 py-3 rounded-xl text-sm flex items-center justify-between transition-all ${i===step?'bg-primary text-white shadow-md':i<step?'hover:bg-muted':'text-muted-foreground opacity-50'}`}><span>{i+1}. {s}</span>{i<step&&<Check className="w-4 h-4"/>}</button>)}</nav></aside><main className="lg:col-span-3"><div className="lg:hidden mb-4"><div className="flex justify-between text-xs font-bold text-muted-foreground mb-2"><span>Step {step+1} of {activeSteps.length}</span><span>{activeSteps[step]}</span></div><div className="h-2 bg-muted rounded-full overflow-hidden"><div className="h-full bg-primary transition-all" style={{width:`${((step+1)/activeSteps.length)*100}%`}}/></div></div><AnimatePresence mode="wait"><motion.section key={step} initial={{opacity:0,x:16}} animate={{opacity:1,x:0}} exit={{opacity:0,x:-16}} transition={{duration:.18}} className="bg-background border border-border rounded-2xl p-5 md:p-8 shadow-sm min-h-[500px] touch-pan-y">{content()}</motion.section></AnimatePresence>{step<activeSteps.length-1&&<div className="flex justify-between mt-5"><button onClick={()=>setStep(s=>Math.max(0,s-1))} disabled={step===0} className="px-5 py-3 rounded-xl font-medium disabled:opacity-30 flex items-center gap-2 hover:bg-muted"><ChevronLeft className="w-4 h-4"/>Back</button><button onClick={next} className="btn-primary px-6 py-3 flex items-center gap-2">Next<ChevronRight className="w-4 h-4"/></button></div>}</main></div></div>;
}
