import React,{useEffect,useState} from 'react';
import {useNavigate,useParams} from 'react-router-dom';
import {AlertTriangle,ArrowLeft,CheckCircle,Download,FileCheck,FileText,MessageSquare,Send,ShieldCheck,Upload,XCircle,Star} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import ProjectChat from '../components/ProjectChat';

type Project={id:string;student_id:string;writer_id:string|null;editor_id:string|null;specification_id:string;title:string;plan:string;status:string;price_ngn:number;revision_limit:number;revisions_used:number;deadline_at:string|null;created_at:string;};
type Specification=Record<string,any>;
type FileRow={id:string;drive_url:string;file_type:string;version:number;is_customer_visible:boolean;created_at:string};
type QA={id:string;decision:string;feedback:string|null;created_at:string;decided_at:string|null};
type Revision={id:string;status:string;request_text:string;points_cost:number;created_at:string};

export default function ProjectWorkspace(){
 const {id}=useParams(); const {user,userData}=useAuth(); const navigate=useNavigate();
 const [project,setProject]=useState<Project|null>(null),[specification,setSpecification]=useState<Specification|null>(null),[file,setFile]=useState<FileRow|null>(null),[qa,setQa]=useState<QA|null>(null),[revision,setRevision]=useState<Revision|null>(null);
 const [loading,setLoading]=useState(true),[driveLink,setDriveLink]=useState(''),[qaFeedback,setQaFeedback]=useState(''),[revisionNotes,setRevisionNotes]=useState(''),[disputeReason,setDisputeReason]=useState(''),[rating,setRating]=useState(5),[reviewText,setReviewText]=useState('');
 const [busy,setBusy]=useState(false),[chat,setChat]=useState(false),[error,setError]=useState(''),[reviewed,setReviewed]=useState(false);

 const load=async()=>{
  if(!id)return; setLoading(true);
  try{
   const {data:p,error:pe}=await supabase.from('projects').select('*').eq('id',id).maybeSingle(); if(pe)throw pe; if(!p)throw new Error('Project not found.'); setProject(p);
   const {data:sp}=await supabase.from('project_specifications').select('*').eq('id',p.specification_id).maybeSingle(); setSpecification(sp||null);
   const {data:files}=await supabase.from('project_files').select('*').eq('project_id',id).order('version',{ascending:false}).order('created_at',{ascending:false}).limit(10); setFile(((files||[]).find((f:any)=>f.is_customer_visible)||(files||[])[0])||null);
   const {data:q}=await supabase.from('qa_reviews').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle(); setQa(q||null);
   const {data:r}=await supabase.from('project_revisions').select('*').eq('project_id',id).order('created_at',{ascending:false}).limit(1).maybeSingle(); setRevision(r||null);
   if(user?.id===p.student_id&&p.status==='completed'){const {data:rv}=await supabase.from('reviews').select('id').eq('project_id',id).eq('reviewer_id',user.id).maybeSingle();setReviewed(Boolean(rv));}
  }catch(e){setError(e instanceof Error?e.message:'Unable to load workspace.');}finally{setLoading(false);}
 };
 useEffect(()=>{void load()},[id,user?.id]);
 const call=async(fn:string,args:Record<string,unknown>)=>{setBusy(true);setError('');try{const {error:e}=await supabase.rpc(fn,args);if(e)throw e;await load();}catch(e){setError(e instanceof Error?e.message:'Action failed.');}finally{setBusy(false);}};
 const submit=()=>id&&driveLink.trim()&&call('submit_project_for_editor',{p_project_id:id,p_drive_url:driveLink.trim(),p_file_type:driveLink.toLowerCase().includes('.pdf')?'pdf':'docx'}).then(()=>setDriveLink(''));
 const approve=()=>id&&call('approve_project_delivery',{p_project_id:id});
 const requestRevision=()=>id&&revisionNotes.trim()&&call('request_project_revision',{p_project_id:id,p_request_text:revisionNotes.trim(),p_points_cost:0}).then(()=>setRevisionNotes(''));
 const raiseDispute=()=>id&&disputeReason.trim()&&call('raise_project_dispute',{p_project_id:id,p_reason:disputeReason.trim()}).then(()=>setDisputeReason(''));
 const acceptRevision=()=>revision&&call('writer_accept_revision',{p_revision_id:revision.id});
 const decide=(d:'approved'|'correction_required')=>id&&call('editor_decide_qa',{p_project_id:id,p_decision:d,p_feedback:qaFeedback.trim()||null}).then(()=>setQaFeedback(''));
 const submitReview=async()=>{if(!id)return;setBusy(true);setError('');try{const {error:e}=await supabase.rpc('submit_project_review',{p_project_id:id,p_rating:rating,p_review_text:reviewText.trim()||null});if(e)throw e;setReviewed(true);setReviewText('');await load();}catch(e){setError(e instanceof Error?e.message:'Unable to submit review.');}finally{setBusy(false);}};

 if(loading)return <div className='p-8 text-center text-muted-foreground'>Loading workspace…</div>;
 if(!project)return <div className='p-8 text-center text-red-500'>{error||'Project not found.'}</div>;
 const isStudent=user?.id===project.student_id,isWriter=user?.id===project.writer_id,isEditor=userData?.role==='editor'&&user?.id===project.editor_id;
 const canRevision=isStudent&&['delivered','editor_approved'].includes(project.status)&&project.revisions_used<project.revision_limit;
 const canAdditionalRevision=isStudent&&['delivered','editor_approved'].includes(project.status)&&project.revisions_used>=project.revision_limit;
 const pendingRevision=isWriter&&revision?.status==='pending'&&project.status==='revision_requested';

 return <div className='w-full max-w-6xl mx-auto px-4 py-6 md:py-8'>
  <button onClick={()=>navigate(-1)} className='flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground mb-6'><ArrowLeft className='w-4 h-4'/>Back</button>
  {error&&<div className='mb-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-500'>{error}</div>}
  <header className='mb-7 border-b border-border pb-6 flex flex-col md:flex-row md:justify-between gap-4'><div><span className='mono-label text-primary'>PROJECT WORKSPACE</span><h1 className='text-2xl md:text-3xl font-bold mt-2'>{project.title}</h1><p className='text-sm text-muted-foreground mt-2'>#{project.id.slice(0,8)} · {project.plan} plan</p></div><span className='text-xs px-3 py-1.5 rounded-md bg-primary/10 text-primary border border-primary/20 font-bold uppercase'>{project.status.replace(/_/g,' ')}</span></header>
  <div className='bento-card p-6 mb-6'><div className='flex items-center justify-between gap-3'><div><h2 className='font-bold text-lg'>Project specification & plan</h2><p className='text-xs text-muted-foreground mt-1'>The exact specification submitted for this commission.</p></div><span className='text-xs font-bold uppercase text-primary'>{project.plan} · ₦{Number(project.price_ngn).toLocaleString('en-NG')}</span></div><div className='grid sm:grid-cols-2 lg:grid-cols-3 gap-3 mt-5'>{Object.entries(specification||{}).filter(([k,v])=>v!==null&&v!==undefined&&v!==''&&!['id','student_id','created_at','updated_at'].includes(k)).slice(0,24).map(([k,v])=><div key={k} className='rounded-xl border border-border p-3'><div className='text-[10px] uppercase tracking-wider font-bold text-muted-foreground'>{k.replace(/_/g,' ')}</div><div className='text-sm font-medium mt-1 break-words'>{typeof v==='object'?JSON.stringify(v):String(v)}</div></div>)}</div></div><div className='grid grid-cols-1 xl:grid-cols-3 gap-6 md:gap-8'><main className='xl:col-span-2 space-y-6'>
   {isWriter&&project.status==='assigned'&&<ActionCard title='Accept Project' text='Accept this paid assignment to begin the delivery window.' button='Accept Project' onClick={()=>call('writer_accept_project',{p_project_id:id!})}/>}
   {pendingRevision&&<ActionCard title='Revision Request' text={revision?.request_text||'The student has requested a revision.'} button='Accept Revision' onClick={acceptRevision}/>} 
   {isWriter&&['in_progress','revision_in_progress','editor_correction_required'].includes(project.status)&&<div className='bento-card p-6 md:p-8'><h2 className='text-xl font-bold flex items-center gap-2 mb-2'><Upload className='w-5 h-5 text-primary'/>Submit Work for QA</h2><p className='text-sm text-muted-foreground mb-5'>Submit the Google Drive link when the PDF/DOCX is ready for Finalyzed Editor review.</p><input value={driveLink} onChange={e=>setDriveLink(e.target.value)} placeholder='https://drive.google.com/…' className='form-input mb-3'/><button disabled={busy||!driveLink.trim()} onClick={submit} className='btn-primary w-full py-3 disabled:opacity-50'><Send className='w-4 h-4 inline mr-2'/>{busy?'Submitting…':'Submit to Editor QA'}</button></div>}
   {isEditor&&project.status==='submitted_for_review'&&<div className='bento-card p-6 md:p-8 border-primary/20'><h2 className='text-xl font-bold flex items-center gap-2'><ShieldCheck className='w-5 h-5 text-primary'/>Editor Quality Assurance</h2><p className='text-sm text-muted-foreground mt-2 mb-5'>Check the submission against the stored project specification before approving it for the student.</p>{file?.drive_url&&<a className='btn-secondary inline-flex items-center gap-2 mb-5' href={file.drive_url} target='_blank' rel='noreferrer'><Download className='w-4 h-4'/>Open submitted document</a>}<textarea value={qaFeedback} onChange={e=>setQaFeedback(e.target.value)} placeholder='QA findings or correction instructions' className='form-input min-h-28 mb-4'/><div className='grid sm:grid-cols-2 gap-3'><button disabled={busy} onClick={()=>decide('correction_required')} className='py-3 rounded-lg border border-red-500/30 text-red-500 font-bold'><XCircle className='w-4 h-4 inline mr-2'/>Correction Required</button><button disabled={busy} onClick={()=>decide('approved')} className='btn-primary py-3'><CheckCircle className='w-4 h-4 inline mr-2'/>Approve for Student</button></div></div>}
   {isWriter&&project.status==='editor_correction_required'&&<div className='bento-card p-6 border-red-500/20 bg-red-500/5'><h2 className='font-bold text-lg'>Editor requested corrections</h2><p className='text-sm text-muted-foreground mt-2'>{qa?.feedback||'Review the latest QA feedback and resubmit the corrected document.'}</p></div>}
   {isStudent&&['delivered','editor_approved'].includes(project.status)&&<div className='bento-card p-6 md:p-8 border-primary/20'><h2 className='text-xl font-bold flex items-center gap-2'><FileCheck className='w-6 h-6 text-primary'/>Your project is ready</h2><p className='text-sm text-muted-foreground mt-2'>The submission has passed Finalyzed QA and is available for your review.</p>{file?.drive_url&&<a href={file.drive_url} target='_blank' rel='noreferrer' className='btn-primary mt-5 inline-flex items-center gap-2'><Download className='w-5 h-5'/>Open / Download Document</a>}<div className='grid md:grid-cols-2 gap-4 mt-6'><div className='bento-card p-5'><b>Revision allowance</b><p className='text-sm text-muted-foreground mt-1'>{project.revisions_used} of {project.revision_limit} used</p></div><div className='bento-card p-5'><b>Delivery</b><p className='text-sm text-muted-foreground mt-1'>Review the files before accepting.</p></div></div><div className='grid md:grid-cols-2 gap-4 mt-5'><button disabled={busy} onClick={approve} className='btn-primary py-3'>Accept Delivery</button><div><textarea disabled={busy||(!canRevision&&!canAdditionalRevision)} value={revisionNotes} onChange={e=>setRevisionNotes(e.target.value)} placeholder={canRevision?'Describe required changes ('+(project.revision_limit-project.revisions_used)+' remaining)':canAdditionalRevision?'Included revisions exhausted — this request uses 100 Finalyzed Points':'Revisions unavailable'} className='form-input min-h-20 mb-2'/><button disabled={busy||(!canRevision&&!canAdditionalRevision)||!revisionNotes.trim()} onClick={requestRevision} className='w-full py-3 rounded-lg border border-primary/30 text-primary font-bold'>{canAdditionalRevision?'Request Revision · 100 Points':'Request Revision'}</button>{canAdditionalRevision&&<div className='mt-5 pt-5 border-t border-border'><div className='flex items-start gap-3'><AlertTriangle className='w-5 h-5 text-amber-500 mt-0.5 shrink-0'/><div><p className='font-semibold'>Still not satisfied?</p><p className='text-xs text-muted-foreground mt-1'>Because the included revisions are exhausted, you can open a formal dispute for administrator review instead of accepting the delivery.</p></div></div><textarea disabled={busy} value={disputeReason} onChange={e=>setDisputeReason(e.target.value)} placeholder='Explain what remains unresolved (minimum 10 characters).' className='form-input min-h-24 mt-4'/><button disabled={busy||!disputeReason.trim()||disputeReason.trim().length<10} onClick={raiseDispute} className='w-full mt-2 py-3 rounded-lg border border-amber-500/30 text-amber-500 font-bold'>{busy?'Opening dispute…':'Open Dispute for Review'}</button></div>}</div></div></div>}
   {isStudent&&project.status==='completed'&&!reviewed&&<div className='bento-card p-6 md:p-8'><h2 className='text-xl font-bold flex items-center gap-2'><Star className='w-5 h-5 text-primary'/>Rate your writer</h2><p className='text-sm text-muted-foreground mt-2'>Your review helps future students choose reliable Finalyzed writers.</p><div className='flex gap-2 mt-5'>{[1,2,3,4,5].map(n=><button key={n} type='button' onClick={()=>setRating(n)} aria-label={n+' stars'} className={'p-1 '+(n<=rating?'text-primary':'text-muted-foreground')}><Star className={'w-7 h-7 '+(n<=rating?'fill-current':'')}/></button>)}</div><textarea value={reviewText} onChange={e=>setReviewText(e.target.value)} placeholder='Tell future students about the service.' className='form-input min-h-24 mt-4'/><button disabled={busy} onClick={submitReview} className='btn-primary w-full py-3 mt-4'>{busy?'Submitting…':'Submit Review'}</button></div>}
   {project.status==='completed'&&reviewed&&<div className='bento-card p-7 flex items-center gap-4'><CheckCircle className='w-9 h-9 text-primary'/><div><h2 className='font-bold text-lg'>Project completed</h2><p className='text-sm text-muted-foreground'>Delivery accepted, payment released and your review has been recorded.</p></div></div>}
  </main><aside className='space-y-6'><div className='bento-card p-6'><h3 className='font-bold flex items-center gap-2'><FileText className='w-4 h-4 text-primary'/>Project details</h3><div className='mt-4 space-y-3 text-sm'><Row label='Plan' value={project.plan}/><Row label='Price' value={'₦'+Number(project.price_ngn).toLocaleString('en-NG')}/><Row label='Revisions' value={project.revisions_used+'/'+project.revision_limit}/><Row label='Deadline' value={project.deadline_at?new Date(project.deadline_at).toLocaleString('en-NG'):'Not assigned'}/></div></div>{revision&&<div className='bento-card p-6'><h3 className='font-bold'>Latest revision</h3><p className='text-xs uppercase text-primary mt-2'>{revision.status.replace(/_/g,' ')}</p><p className='text-sm text-muted-foreground mt-2'>{revision.request_text}</p>{revision.points_cost>0&&<p className='text-xs mt-2'>Points used: {revision.points_cost}</p>}</div>}{qa&&<div className='bento-card p-6'><h3 className='font-bold'>Latest QA</h3><p className='text-sm mt-2 capitalize'>{qa.decision.replace(/_/g,' ')}</p>{qa.feedback&&<p className='text-sm text-muted-foreground mt-2'>{qa.feedback}</p>}</div>}{chat?<ProjectChat projectId={id!} onClose={()=>setChat(false)}/>:<div className='bento-card p-6'><h3 className='font-bold flex items-center gap-2'><MessageSquare className='w-4 h-4 text-primary'/>Communication</h3><p className='text-sm text-muted-foreground mt-2 mb-4'>Keep project communication inside the workspace.</p><button onClick={()=>setChat(true)} className='btn-secondary w-full'>Open Chat</button></div>}</aside></div></div>;
}
function Row({label,value}:{label:string;value:string}){return <div className='flex justify-between gap-4'><span className='text-muted-foreground'>{label}</span><span className='font-semibold capitalize text-right'>{value}</span></div>}
function ActionCard({title,text,button,onClick}:{title:string;text:string;button:string;onClick:()=>void}){return <div className='bento-card p-7'><CheckCircle className='w-7 h-7 text-primary mb-3'/><h2 className='text-xl font-bold'>{title}</h2><p className='text-sm text-muted-foreground mt-2 mb-5'>{text}</p><button onClick={onClick} disabled={false} className='btn-primary py-3 px-6'>{button}</button></div>}