import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {FileText,Clock,Wallet,CheckCircle,TrendingUp,RefreshCw,ChevronRight} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';
import DashboardAnalytics from '../components/DashboardAnalytics';
import RoleOperationsOverview from '../components/RoleOperationsOverview';
const label=(s:string)=>String(s||'').replace(/_/g,' ');
export default function SpecialistDashboard(){
 const {user,userData}=useAuth();const [available,setAvailable]=useState<any[]>([]);const [projects,setProjects]=useState<any[]>([]);const [revisions,setRevisions]=useState<any[]>([]);const [wallet,setWallet]=useState<any>(null);const [filter,setFilter]=useState('active');const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user)return;let live=true;(async()=>{const [p,w,a]=await Promise.all([supabase.from('projects').select('*').eq('writer_id',user.id).order('created_at',{ascending:false}),supabase.from('wallets').select('*').eq('user_id',user.id).maybeSingle(),supabase.rpc('get_available_writer_projects')]);const rows=p.data||[];let rev:any[]=[];if(rows.length){const q=await supabase.from('project_revisions').select('*').in('project_id',rows.map(x=>x.id)).order('created_at',{ascending:false});rev=q.data||[]}if(live){setProjects(rows);setRevisions(rev);setWallet(w.data||null);setAvailable(a.data||[]);setLoading(false)}})();return()=>{live=false}},[user]);
 const shown=useMemo(()=>filter==='all'?projects:filter==='active'?projects.filter(p=>!['completed','cancelled'].includes(p.status)):projects.filter(p=>p.status===filter),[projects,filter]); const pending=revisions.filter(r=>['requested','pending','accepted'].includes(r.status));
 if(loading)return <div className="p-8 text-center text-muted-foreground">Loading writer portal…</div>;
 return <div className="w-full px-4 sm:px-6 lg:px-8 py-8 space-y-6"><header><span className="mono-label">Finalyzed Writer Portal</span><h1 className="text-3xl font-light mt-2">Welcome, <b>{userData?.name?.split(' ')[0]||'Finalyzed Writer'}</b></h1><p className="text-sm text-muted-foreground mt-2">Assignments, revisions, deadlines and earnings stay connected to each project.</p></header>
 <div className="grid sm:grid-cols-2 lg:grid-cols-4 gap-4"><Metric icon={<Wallet/>} label="Available cash" value={'₦'+Number(wallet?.balance_ngn||0).toLocaleString('en-NG')}/><Metric icon={<TrendingUp/>} label="Finalyzed Points" value={Number(wallet?.points_balance||0).toLocaleString()}/><Metric icon={<CheckCircle/>} label="Completed" value={String(projects.filter(p=>p.status==='completed').length)}/><Metric icon={<Clock/>} label="Active" value={String(projects.filter(p=>!['completed','cancelled'].includes(p.status)).length)}/></div>
 <RoleOperationsOverview role="writer" userId={user.id}/><DashboardAnalytics role="writer" projects={projects} revisions={revisions}/><section className="bento-card p-6"><div className="flex items-center justify-between gap-3 mb-4"><div><h2 className="text-xl font-bold">Available projects</h2><p className="text-sm text-muted-foreground">Paid projects currently waiting for a Finalyzed Writer assignment.</p></div><span className="badge-verified">{available.length} available</span></div>{available.length===0?<p className="text-sm text-muted-foreground py-5 text-center">No unassigned paid projects are waiting right now.</p>:<div className="divide-y divide-border">{available.map(p=><Link key={p.id} to={'/workspace/'+p.id} className="flex items-center justify-between gap-4 py-4"><div><p className="font-semibold">{p.title}</p><p className="text-sm text-muted-foreground">{p.plan} · ₦{Number(p.price_ngn||0).toLocaleString('en-NG')}</p></div><ChevronRight className="w-4 h-4 text-primary"/></Link>)}</div>}</section>
 <section className="bento-card p-6"><div className="flex items-center gap-3 mb-4"><RefreshCw className="w-5 h-5 text-primary"/><div><h2 className="text-xl font-bold">Revision Queue</h2><p className="text-sm text-muted-foreground">Student requests that require your attention.</p></div></div>{pending.length===0?<p className="text-muted-foreground py-6 text-center">No pending revision requests.</p>:<div className="divide-y divide-border">{pending.map(r=><Link key={r.id} to={'/workspace/'+r.project_id} className="flex items-center justify-between gap-3 py-4"><div><p className="font-semibold">{r.request_text||'Revision requested'}</p><p className="text-xs text-muted-foreground mt-1">Status: {label(r.status)}</p></div><ChevronRight className="w-4 h-4"/></Link>)}</div>}</section>
 <section className="bento-card p-6"><div className="flex flex-col sm:flex-row sm:justify-between sm:items-center gap-3 mb-5"><h2 className="text-xl font-bold">My Projects</h2><div className="flex gap-2">{['active','all','completed','editor_correction_required'].map(f=><button key={f} onClick={()=>setFilter(f)} className={'px-3 py-1.5 rounded-full text-xs font-semibold border '+(filter===f?'bg-primary text-primary-foreground border-primary':'border-border text-muted-foreground')}>{f==='editor_correction_required'?'Corrections':f[0].toUpperCase()+f.slice(1)}</button>)}</div></div>{shown.length===0?<p className="text-muted-foreground py-8 text-center">No projects in this view.</p>:<div className="divide-y divide-border">{shown.map(p=><Link key={p.id} to={'/workspace/'+p.id} className="flex flex-col sm:flex-row sm:justify-between gap-3 py-5 px-2 hover:bg-muted/30 rounded-lg"><div><h3 className="font-semibold">{p.title}</h3><p className="text-sm text-muted-foreground mt-1">{p.plan} · deadline {p.deadline_at?new Date(p.deadline_at).toLocaleString('en-NG'):'not assigned'}</p></div><div className="flex items-center gap-2"><span className="text-xs uppercase font-bold text-primary">{label(p.status)}</span><ChevronRight className="w-4 h-4"/></div></Link>)}</div>}</section></div>
}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="bento-card p-6"><div className="w-5 h-5 text-primary">{icon}</div><p className="text-xs uppercase tracking-wider text-muted-foreground mt-3">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
