import React,{useEffect,useMemo,useState} from 'react';
import {Link} from 'react-router-dom';
import {BookOpen,Clock,CheckCircle,Shield,Zap,ChevronRight,RefreshCw,Plus} from 'lucide-react';
import {useAuth} from '../contexts/AuthContext';
import {supabase} from '../lib/supabase';

const label=(s:string)=>String(s||'').replace(/_/g,' ');
const statusTone=(s:string)=>s==='completed'?'text-emerald-600':s==='cancelled'||s==='disputed'?'text-red-500':s==='editor_correction_required'||s==='revision_requested'?'text-amber-600':'text-primary';

export default function StudentDashboard(){
 const {user,userData}=useAuth(); const [projects,setProjects]=useState<any[]>([]); const [revisions,setRevisions]=useState<any[]>([]); const [wallet,setWallet]=useState<any>(null); const [filter,setFilter]=useState('all'); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!user)return; let live=true;(async()=>{const [p,w]=await Promise.all([supabase.from('projects').select('*').eq('student_id',user.id).order('created_at',{ascending:false}),supabase.from('wallets').select('*').eq('user_id',user.id).maybeSingle()]);const rows=p.data||[];let rev:any[]=[];if(rows.length){const q=await supabase.from('project_revisions').select('*').in('project_id',rows.map(x=>x.id)).order('created_at',{ascending:false});rev=q.data||[]}if(live){setProjects(rows);setRevisions(rev);setWallet(w.data||null);setLoading(false)}})();return()=>{live=false}},[user]);
 const shown=useMemo(()=>filter==='all'?projects:projects.filter(p=>filter==='active'?!['completed','cancelled'].includes(p.status):p.status===filter),[projects,filter]);
 if(loading)return <div className="p-8 text-center text-muted-foreground">Loading student portal…</div>;
 const active=projects.filter(p=>!['completed','cancelled'].includes(p.status)); const completed=projects.filter(p=>p.status==='completed'); const pendingRevisions=revisions.filter(r=>['requested','pending','accepted'].includes(r.status));
 return <div className="w-full px-4 sm:px-6 lg:px-8 py-6 md:py-8 space-y-6">
  <header className="flex flex-col md:flex-row md:items-end md:justify-between gap-4"><div><span className="mono-label">Student Portal</span><h1 className="text-3xl font-light mt-2">Welcome back, <b>{userData?.name?.split(' ')[0]||'Student'}</b></h1><p className="text-sm text-muted-foreground mt-2">Track every project, delivery, revision and approval from one place.</p></div><Link to="/start-project" className="btn-primary px-6 py-3 flex items-center justify-center gap-2"><Plus className="w-4 h-4"/>Create Project</Link></header>
  <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4"><Metric icon={<Zap/>} label="Finalyzed Points" value={Number(wallet?.points_balance||0).toLocaleString()} hint="1 point = ₦10"/><Metric icon={<BookOpen/>} label="Active Projects" value={String(active.length)}/><Metric icon={<CheckCircle/>} label="Completed" value={String(completed.length)}/></div>
  {pendingRevisions.length>0&&<section className="bento-card p-6 border-primary/20"><div className="flex items-center justify-between mb-4"><div><span className="mono-label text-primary">Action required</span><h2 className="text-xl font-bold mt-1">Revision activity</h2></div><RefreshCw className="w-5 h-5 text-primary"/></div><div className="space-y-2">{pendingRevisions.map(r=><Link key={r.id} to={'/workspace/'+r.project_id} className="flex items-center justify-between gap-3 rounded-xl border border-border p-4 hover:border-primary/30"><div><p className="font-semibold">Revision request</p><p className="text-sm text-muted-foreground">{r.request_text||'Revision requested for this project.'}</p></div><span className="text-xs font-bold uppercase text-primary">{label(r.status)}</span></Link>)}</div></section>}
  <section className="bento-card p-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3 mb-5"><h2 className="text-xl font-bold">My Projects</h2><div className="flex flex-wrap gap-2">{['all','active','completed'].map(f=><button key={f} onClick={()=>setFilter(f)} className={'px-3 py-1.5 rounded-full text-xs font-semibold border '+(filter===f?'bg-primary text-primary-foreground border-primary':'border-border text-muted-foreground')}>{f==='all'?'All':f==='active'?'Active':'Completed'}</button>)}</div></div>{shown.length===0?<div className="text-center py-10"><BookOpen className="w-10 h-10 mx-auto opacity-20 mb-3"/><p className="text-muted-foreground">No projects in this view.</p></div>:<div className="divide-y divide-border">{shown.map(p=><Link key={p.id} to={'/workspace/'+p.id} className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 py-5 px-2 hover:bg-muted/30 rounded-lg"><div className="min-w-0"><h3 className="font-semibold truncate">{p.title}</h3><p className="text-sm text-muted-foreground mt-1">{p.plan} · {p.revisions_used}/{p.revision_limit} revisions used</p></div><div className="flex items-center gap-2 shrink-0"><span className={'text-xs uppercase font-bold '+statusTone(p.status)}>{label(p.status)}</span><ChevronRight className="w-4 h-4 text-muted-foreground"/></div></Link>)}</div>}</section>
  <div className="text-xs text-muted-foreground flex items-center gap-2"><Clock className="w-3 h-3"/> Statuses are synchronized with the Finalyzed workflow.</div>
 </div>;
}
function Metric({icon,label,value,hint}:{icon:React.ReactNode;label:string;value:string;hint?:string}){return <div className="bento-card p-6"><div className="w-5 h-5 text-primary">{icon}</div><p className="text-xs uppercase tracking-wider text-muted-foreground mt-3">{label}</p><p className="text-2xl font-bold mt-1">{value}</p>{hint&&<p className="text-xs text-muted-foreground mt-1">{hint}</p>}</div>}
