import React,{useMemo} from 'react';
import {ResponsiveContainer,AreaChart,Area,BarChart,Bar,LineChart,Line,PieChart,Pie,Cell,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';

type Props={role:'student'|'writer'|'editor'|'admin';projects?:any[];revisions?:any[];reviews?:any[];payments?:any[]};
const STATUS=['pending','paid','in_progress','submitted_for_review','editor_correction_required','revision_requested','completed','cancelled'];
const pretty=(s:string)=>String(s||'').replace(/_/g,' ').replace(/\b\w/g,m=>m.toUpperCase());
const months=['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
const month=(d:any)=>{const x=new Date(d);return Number.isNaN(x.getTime())?'Unknown':x.toLocaleString('en-US',{month:'short'})};
export default function DashboardAnalytics({role,projects=[],revisions=[],reviews=[],payments=[]}:Props){
 const status=useMemo(()=>STATUS.map(s=>({name:pretty(s),value:projects.filter(p=>p.status===s).length})).filter(x=>x.value),[projects]);
 const monthly=useMemo(()=>{const m=months.map(name=>({name,projects:0,completed:0,revenue:0,reviews:0}));projects.forEach(p=>{const i=months.indexOf(month(p.created_at));if(i>=0){m[i].projects++;if(p.status==='completed')m[i].completed++}});payments.filter(p=>p.status==='completed').forEach(p=>{const i=months.indexOf(month(p.created_at));if(i>=0)m[i].revenue+=Number(p.amount_ngn||0)});reviews.forEach(r=>{const i=months.indexOf(month(r.created_at));if(i>=0)m[i].reviews++});return m.filter((_,i)=>projects.some(p=>months.indexOf(month(p.created_at))===i)||payments.some(p=>months.indexOf(month(p.created_at))===i)||reviews.some(r=>months.indexOf(month(r.created_at))===i)).slice(-6)},[projects,payments,reviews]);
 const plans=useMemo(()=>['basic','standard','premium'].map(name=>({name:pretty(name),count:projects.filter(p=>String(p.plan||'').toLowerCase()===name).length})).filter(x=>x.count),[projects]);
 const revs=useMemo(()=>{const c:any={requested:0,pending:0,accepted:0,completed:0,rejected:0};revisions.forEach(r=>{if(r.status in c)c[r.status]++});return Object.entries(c).filter(([,v])=>Number(v)).map(([name,value])=>({name:pretty(name),value:Number(value)}))},[revisions]);
 const cells=['#337179','#5b8f94','#82aaad','#a9c5c7','#234f54','#6b7d80'];
 const tip={contentStyle:{borderRadius:12,border:'1px solid #e5e7eb',background:'#fff'}};
 if(!projects.length&&!payments.length&&!reviews.length&&!revisions.length)return <section className="bento-card p-6"><span className="mono-label text-primary">Analytics</span><h2 className="text-xl font-bold mt-1">Your activity will appear here</h2><p className="text-sm text-muted-foreground mt-2">Live analytics will populate automatically as Finalyzed activity is recorded.</p></section>;
 return <section className="space-y-4" aria-label="Dashboard analytics"><div className="flex items-end justify-between"><div><span className="mono-label text-primary">Live Analytics</span><h2 className="text-xl sm:text-2xl font-bold mt-1">{role==='admin'?'Platform overview':role==='student'?'Project overview':role==='writer'?'Performance overview':'Quality overview'}</h2></div><span className="text-xs text-muted-foreground">Live dashboard data</span></div><div className="grid lg:grid-cols-2 gap-4">
 <ChartCard title="Project activity" subtitle="Created vs completed"><ResponsiveContainer width="100%" height={240}><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip {...tip}/><Legend/><Area type="monotone" dataKey="projects" name="Projects" stroke="#337179" fill="#337179" fillOpacity={0.14}/><Area type="monotone" dataKey="completed" name="Completed" stroke="#6b7d80" fill="#6b7d80" fillOpacity={0.08}/></AreaChart></ResponsiveContainer></ChartCard>
 <ChartCard title="Project status" subtitle="Current workflow distribution"><ResponsiveContainer width="100%" height={240}><PieChart><Pie data={status} dataKey="value" nameKey="name" cx="50%" cy="50%" innerRadius={60} outerRadius={86} paddingAngle={3}>{status.map((_,i)=><Cell key={i} fill={cells[i%cells.length]}/>)}</Pie><Tooltip {...tip}/></PieChart></ResponsiveContainer></ChartCard>
 <ChartCard title={role==='admin'?'Revenue trend':role==='editor'?'Review workload':'Plan mix'} subtitle={role==='admin'?'Completed payment volume':role==='editor'?'Reviews by month':'Projects by plan'}><ResponsiveContainer width="100%" height={240}>{role==='admin'?<BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip {...tip}/><Bar dataKey="revenue" name="Revenue (₦)" fill="#337179" radius={[5,5,0,0]}/></BarChart>:role==='editor'?<LineChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip {...tip}/><Line type="monotone" dataKey="reviews" name="Reviews" stroke="#337179" strokeWidth={3} dot={{r:3}}/></LineChart>:<BarChart data={plans}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip {...tip}/><Bar dataKey="count" name="Projects" fill="#337179" radius={[5,5,0,0]}/></BarChart>}</ResponsiveContainer></ChartCard>
 <ChartCard title={role==='writer'||role==='student'?'Revision activity':'Revision queue'} subtitle="Revision lifecycle"><ResponsiveContainer width="100%" height={240}><BarChart data={revs}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis allowDecimals={false}/><Tooltip {...tip}/><Bar dataKey="value" name="Revisions" radius={[5,5,0,0]}>{revs.map((_,i)=><Cell key={i} fill={cells[i%cells.length]}/>)}</Bar></BarChart></ResponsiveContainer></ChartCard>
 </div></section>;
}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <div className="bento-card p-4 sm:p-5 min-w-0"><div className="mb-3"><h3 className="font-bold">{title}</h3><p className="text-xs text-muted-foreground mt-1">{subtitle}</p></div><div className="w-full min-w-0">{children}</div></div>}
