import React,{useEffect,useState} from 'react';
import {Plus,Search,Check} from 'lucide-react';
import {supabase} from '../lib/supabase';

export default function InstitutionPicker({value,onChange,required=false}:{value:string;onChange:(value:string)=>void;required?:boolean}){
 const [items,setItems]=useState<any[]>([]); const [query,setQuery]=useState(''); const [other,setOther]=useState(false); const [newName,setNewName]=useState(''); const [saving,setSaving]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{void (async()=>{const {data}=await supabase.from('institutions').select('id,name,ownership,state,verified').order('name');setItems(data||[])})()},[]);
 const filtered=items.filter(i=>i.name.toLowerCase().includes(query.toLowerCase()));
 const add=async()=>{if(!newName.trim())return;setSaving(true);setMessage('');const {data,error}=await supabase.rpc('add_institution',{p_name:newName.trim(),p_state:null,p_ownership:'other'});if(error){setMessage(error.message)}else{const name=data?.name||newName.trim();setItems(v=>[...v,{id:data?.id,name,ownership:'other',verified:false}].sort((a,b)=>a.name.localeCompare(b.name)));onChange(name);setOther(false);setNewName('');setMessage('Institution added. It will be reviewed by Finalyzed.')}setSaving(false)};
 return <div className="space-y-2"><span className="text-sm font-semibold">Institution{required&&<span className="text-primary"> *</span>}</span>{other?<div className="flex gap-2"><input value={newName} onChange={e=>setNewName(e.target.value)} className="form-input flex-1" placeholder="Enter your institution's full name"/><button type="button" onClick={()=>void add()} disabled={saving||!newName.trim()} className="btn-primary px-4"><Check className="w-4 h-4"/></button></div>:<select value={value} required={required} onChange={e=>e.target.value==='__OTHER__'?setOther(true):onChange(e.target.value)} className="form-input"><option value="">Select institution</option>{filtered.map(i=><option key={i.id} value={i.name}>{i.name}{i.ownership&&i.ownership!=='other'?' · '+i.ownership:''}</option>)}<option value="__OTHER__">Other — add institution</option></select>}{items.length>20&&<label className="relative block"><Search className="w-4 h-4 absolute left-3 top-3 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="form-input pl-9 text-sm" placeholder="Search institutions"/></label>}{message&&<p className="text-xs text-primary flex items-center gap-1"><Plus className="w-3 h-3"/>{message}</p>}</div>
}
