import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Search,Check,ChevronDown} from 'lucide-react';
import {supabase} from '../lib/supabase';

export default function InstitutionPicker({value,onChange,required=false}:{value:string;onChange:(value:string)=>void;required?:boolean}){
 const [items,setItems]=useState<any[]>([]);const [query,setQuery]=useState('');const [other,setOther]=useState(false);const [newName,setNewName]=useState('');const [newType,setNewType]=useState<'university'|'polytechnic'>('university');const [saving,setSaving]=useState(false);const [message,setMessage]=useState('');
 useEffect(()=>{void(async()=>{const {data}=await supabase.from('institutions').select('id,name,ownership,state,verified,institution_type').order('name');setItems(data||[])})()},[]);
 const filtered=useMemo(()=>items.filter(i=>String(i.name||'').toLowerCase().includes(query.toLowerCase())),[items,query]);
 const grouped=(type:string)=>filtered.filter(i=>(i.institution_type||'university')===type);
 const add=async()=>{if(!newName.trim())return;setSaving(true);setMessage('');const {data,error}=await supabase.rpc('add_institution',{p_name:newName.trim(),p_state:null,p_ownership:'other',p_institution_type:newType});if(error)setMessage(error.message);else{const row={id:data?.id,name:data?.name||newName.trim(),ownership:'other',verified:false,institution_type:data?.institution_type||newType};setItems(v=>[...v,row].sort((a,b)=>a.name.localeCompare(b.name)));onChange(row.name);setOther(false);setNewName('');setMessage('Institution added. It will be reviewed by Finalyzed.')}setSaving(false)};
 return <div className="space-y-2"><span className="text-sm font-semibold">Institution{required&&<span className="text-primary"> *</span>}</span>{other?<div className="space-y-2 rounded-xl border border-border p-3"><div className="grid sm:grid-cols-[1fr_180px_auto] gap-2"><input value={newName} onChange={e=>setNewName(e.target.value)} className="form-input" placeholder="Enter your institution's full name"/><select value={newType} onChange={e=>setNewType(e.target.value as any)} className="form-input"><option value="university">University</option><option value="polytechnic">Polytechnic</option></select><button type="button" onClick={()=>void add()} disabled={saving||!newName.trim()} className="btn-primary px-4"><Check className="w-4 h-4"/></button></div><button type="button" onClick={()=>setOther(false)} className="text-xs text-muted-foreground hover:text-foreground">Back to catalogue</button></div>:<div className="relative"><select value={value} required={required} onChange={e=>e.target.value==='__OTHER__'?setOther(true):onChange(e.target.value)} className="form-input pr-10"><option value="">Select institution</option>{grouped('university').length>0&&<optgroup label="Universities">{grouped('university').map(i=><option key={i.id} value={i.name}>{i.name}{i.ownership&&i.ownership!=='other'?' · '+i.ownership:''}</option>)}</optgroup>}{grouped('polytechnic').length>0&&<optgroup label="Polytechnics">{grouped('polytechnic').map(i=><option key={i.id} value={i.name}>{i.name}{i.ownership&&i.ownership!=='other'?' · '+i.ownership:''}</option>)}</optgroup>}<option value="__OTHER__">Other — add institution</option></select><ChevronDown className="pointer-events-none absolute right-3 top-3.5 w-4 h-4 text-muted-foreground"/></div>}{items.length>20&&<label className="relative block"><Search className="w-4 h-4 absolute left-3 top-3 text-muted-foreground"/><input value={query} onChange={e=>setQuery(e.target.value)} className="form-input pl-9 text-sm" placeholder="Search universities and polytechnics…"/></label>}{message&&<p className="text-xs text-primary flex items-center gap-1"><Plus className="w-3 h-3"/>{message}</p>}</div>
}
