import React,{useEffect,useState} from 'react';
import {CheckCircle2,Plus,Trash2,Save,Building2} from 'lucide-react';
import {supabase} from '../lib/supabase';

export type TemplateField={key:string;label:string;type:'text'|'textarea'|'select'|'number'|'checkbox'|'multiselect';placeholder?:string;required?:boolean;options?:string[]};
export type TemplateStep={title:string;description:string;fields:TemplateField[]};

export const FINALYZED_DEFAULT_TEMPLATE:TemplateStep[]=[
{title:'Student Information',description:'Academic identity and submission context.',fields:[
{key:'fullName',label:'Full name',type:'text',required:true},{key:'matricNumber',label:'Matriculation / registration number',type:'text',required:true},{key:'institution',label:'Institution',type:'select',required:true},{key:'faculty',label:'Faculty / school',type:'text',required:true},{key:'department',label:'Department',type:'text',required:true},{key:'degree',label:'Degree / award',type:'select',required:true,options:['ND','HND','BSc','BA','BEng','BTech','LLB','MBBS','MSc','MA','MEng','Other']},{key:'supervisor',label:'Project supervisor',type:'text'},{key:'hod',label:'Head of department',type:'text'},{key:'submissionMonth',label:'Submission month',type:'select',options:['January','February','March','April','May','June','July','August','September','October','November','December']},{key:'submissionYear',label:'Submission year',type:'select',options:Array.from({length:10},(_,i)=>String(new Date().getFullYear()+i))}]},
{title:'Project Identity',description:'What the specialist is being commissioned to deliver.',fields:[
{key:'projectTitle',label:'Exact approved project title',type:'text',required:true},{key:'projectType',label:'Project type',type:'select',required:true,options:['Design & Construction','Research Study','Software Development','Case Study','Business Plan','Survey-Based Study','Literature Review','Other']},{key:'subjectArea',label:'Core subject matter / technology / method',type:'text'},{key:'problemStatement',label:'Problem being addressed',type:'textarea'},{key:'aimObjectives',label:'Aim and objectives',type:'textarea'},{key:'expectedOutcome',label:'Target outcome / result',type:'textarea'},{key:'supervisorInstructions',label:'Supervisor instructions',type:'textarea'},{key:'topicApproved',label:'Topic officially approved?',type:'checkbox'}]},
{title:'Institution Requirements',description:'Department-specific rules become part of the QA checklist.',fields:[
{key:'hasPrescribedFormat',label:'Does your institution have a prescribed project format?',type:'select',options:['Yes','No','Unknown']},{key:'prescribedFormatDetails',label:'Prescribed format details',type:'textarea'},{key:'preliminaryPages',label:'Required preliminary pages',type:'textarea',placeholder:'Certification, Dedication, Acknowledgement, Abstract, TOC…'},{key:'institutionStructure',label:'Required chapter structure / department rules',type:'textarea'},{key:'standardsBodies',label:'Relevant standards / regulatory bodies',type:'textarea'},{key:'ethicalRequirements',label:'Ethical, safety, data-protection or institutional requirements',type:'textarea'}]},
{title:'Formatting',description:'Formatting rules used by writers and editors.',fields:[
{key:'fontFamily',label:'Font family',type:'select',options:['Times New Roman','Arial','Calibri','Georgia','Institution Standard','Other']},{key:'bodyFontSize',label:'Body font size (pt)',type:'select',options:['10','11','12','13','14']},{key:'headingFontSize',label:'Heading font size (pt)',type:'select',options:['12','13','14','15','16','18']},{key:'lineSpacing',label:'Line spacing',type:'select',options:['1.0','1.15','1.5','2.0','Institution Standard']},{key:'alignment',label:'Body alignment',type:'select',options:['Justified','Left','Institution Standard']},{key:'paragraphIndentation',label:'Paragraph indentation',type:'select',options:['None','0.25 inch','0.5 inch','1 inch','Institution Standard']},{key:'marginLeft',label:'Left margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginRight',label:'Right margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginTop',label:'Top margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginBottom',label:'Bottom margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'preliminaryNumbering',label:'Preliminary numbering',type:'select',options:['Roman numerals','Arabic numerals','Institution Standard']},{key:'chapterNumbering',label:'Chapter numbering',type:'select',options:['Arabic numerals','Institution Standard']},{key:'headerFooterRules',label:'Header / footer rules',type:'textarea'},{key:'tableFigureRules',label:'Table / figure / caption rules',type:'textarea'}]},
{title:'Page & Length',description:'Requested length and page-budget rules.',fields:[
{key:'minPages',label:'Minimum pages',type:'number'},{key:'targetPages',label:'Target pages',type:'number',required:true},{key:'maxPages',label:'Maximum pages',type:'number'},{key:'countPrelim',label:'Preliminary pages count',type:'checkbox'},{key:'countReferences',label:'References count',type:'checkbox'},{key:'countAppendices',label:'Appendices count',type:'checkbox'},{key:'pageBudgetInstructions',label:'Page-budget / length instructions',type:'textarea'}]},
{title:'Structure',description:'Define the chapter architecture.',fields:[
{key:'chapterCount',label:'Number of chapters',type:'select',options:['3','4','5','6','7','8']},{key:'mandatorySubsections',label:'Mandatory sections / subsections',type:'textarea'},{key:'excludedSections',label:'Sections that must be excluded',type:'textarea'}]},
{title:'Citation & References',description:'Citation style and source requirements.',fields:[
{key:'citationStyle',label:'Citation style',type:'select',required:true,options:['APA 7th','IEEE','Harvard','MLA','Vancouver','Chicago','Institution Standard','Other']},{key:'minReferences',label:'Minimum references',type:'number'},{key:'maxReferences',label:'Maximum references',type:'number'},{key:'sourceRequirements',label:'Source requirements',type:'textarea'},{key:'requiredReferences',label:'Required standards / datasheets / regulatory references',type:'textarea'}]},
{title:'Methodology / Design',description:'How the work should be conducted, built, tested or analysed.',fields:[
{key:'methodology',label:'Methodology / research design / system architecture',type:'textarea',required:true},{key:'technologies',label:'Required technologies / instruments / tools',type:'text'},{key:'scope',label:'Population, sample, scope or system boundary',type:'textarea'},{key:'dataCollectionMethod',label:'Sampling / data collection method',type:'textarea'},{key:'analysisMethod',label:'Analysis / calculation / testing method',type:'textarea'},{key:'complianceApproach',label:'Safety, ethical and regulatory compliance approach',type:'textarea'},{key:'designJustification',label:'Design decisions and justification',type:'textarea'}]},
{title:'Data & Results',description:'Evidence and measurable outcomes.',fields:[
{key:'hasRealData',label:'Do you already have real project data?',type:'select',options:['Yes','No','Partial']},{key:'availableData',label:'Available data / results',type:'textarea'},{key:'resultRequirements',label:'Expected results, tables, charts, diagrams or technical drawings',type:'textarea'},{key:'targetOutcomeMetric',label:'Target performance / measurable outcome',type:'text'},{key:'testingRequirements',label:'Testing / validation requirements',type:'textarea'}]},
{title:'Appendices',description:'Supporting material for the final deliverable.',fields:[
{key:'appendices',label:'Appendices required',type:'multiselect',options:['Questionnaire','Interview Questions','Test Log','Bill of Materials','Budget','Code Listing','Technical Drawings','Financial Statements','Reference Tables','Implementation Timeline']},{key:'otherAppendices',label:'Other appendices',type:'text'},{key:'appendixInstructions',label:'Appendix-specific instructions',type:'textarea'}]},
{title:'Presentation',description:'Presentation deliverables.',fields:[
{key:'presentationRequired',label:'Project presentation is required',type:'checkbox'},{key:'slideCount',label:'Expected slide count',type:'select',options:['10–15','15–20','20–25','25–30','30+']},{key:'presentationStyle',label:'Presentation style',type:'select',options:['Academic defence','Institution template','Minimal professional','Other']},{key:'defenceRequirements',label:'Defence requirements / likely questions',type:'textarea'},{key:'presentationGuideRequired',label:'Simplified presentation guide is required',type:'checkbox'}]},
{title:'Special Instructions',description:'Anything important that does not fit elsewhere.',fields:[
{key:'specialInstructions',label:'Special instructions',type:'textarea'},{key:'doNotChange',label:'Things the writer must NOT change',type:'textarea'},{key:'deliveryInstructions',label:'Expected communication / delivery instructions',type:'textarea'},{key:'otherNotes',label:'Other notes from supervisor or department',type:'textarea'}]}
];

export default function ProjectTemplateManager(){
 const [institutions,setInstitutions]=useState<any[]>([]);
 const [selectedInstitution,setSelectedInstitution]=useState('');
 const [name,setName]=useState('');
 const [description,setDescription]=useState('');
 const [answers,setAnswers]=useState<Record<string,any>>({});
 const [step,setStep]=useState(0);
 const [saving,setSaving]=useState(false);
 const [syncing,setSyncing]=useState(false);
 const [message,setMessage]=useState('');
 const [errors,setErrors]=useState<string[]>([]);

 useEffect(()=>{void loadInstitutions()},[]);
 const loadInstitutions=async()=>{const {data}=await supabase.from('institutions').select('id,name,ownership,state,institution_type,verified').order('name');setInstitutions(data||[])};
 const update=(key:string,value:any)=>{setAnswers(v=>({...v,[key]:value}));setErrors([])};
 const current=FINALYZED_DEFAULT_TEMPLATE[step];
 const validate=()=>{const missing=current.fields.filter(f=>{const v=answers[f.key];if(f.type==='checkbox')return typeof v!=='boolean';if(f.type==='multiselect')return !Array.isArray(v)||v.length===0;return String(v??'').trim()===''}).map(f=>f.label);setErrors(missing);return missing.length===0};
 const save=async()=>{if(!selectedInstitution||!name.trim()){setMessage('Choose an institution and name the template.');return}for(let i=0;i<FINALYZED_DEFAULT_TEMPLATE.length;i++){const fields=FINALYZED_DEFAULT_TEMPLATE[i].fields;const missing=fields.filter(f=>{const v=answers[f.key];if(f.type==='checkbox')return typeof v!=='boolean';if(f.type==='multiselect')return !Array.isArray(v)||v.length===0;return String(v??'').trim()===''});if(missing.length){setStep(i);setErrors(missing.map(f=>f.label));setMessage('Complete every question before publishing this template.');return}}setSaving(true);setMessage('');try{const {error}=await supabase.from('institution_templates').insert({institution_id:selectedInstitution,name:name.trim(),description:description.trim(),specification_schema:FINALYZED_DEFAULT_TEMPLATE,specification_defaults:answers,verified:true,is_student_derived:false});if(error)throw error;setMessage('Template published to the Finalyzed Knowledge Base.');setAnswers({});setStep(0);setName('');setDescription('');}catch(e){setMessage(e instanceof Error?e.message:'Unable to publish template.')}finally{setSaving(false)}};
 return <section className="space-y-6">
  <div className="bento-card p-6 md:p-8">
   <div className="flex flex-col lg:flex-row lg:items-start lg:justify-between gap-5">
    <div><div className="mono-label text-primary flex items-center gap-2"><Building2 className="w-4 h-4"/>Knowledge Base · Template Studio</div><h1 className="text-2xl md:text-3xl font-bold mt-2">Create an institutional project template</h1><p className="text-sm text-muted-foreground mt-2 max-w-3xl">Fill the same 13-stage project specification students use. Your completed answers become the reusable template students can preview and use.</p></div>
    <button onClick={async()=>{setSyncing(true);setMessage('Refreshing universities and polytechnics from the official registries…');try{const r=await fetch('/.netlify/functions/national-institutions');const p=await r.json();if(!r.ok)throw new Error(p.error||'Institution sync failed.');const x=await supabase.rpc('admin_import_institutions',{p_institutions:p.institutions});if(x.error)throw x.error;await loadInstitutions();setMessage('Institution catalogue refreshed.')}catch(e){setMessage(e instanceof Error?e.message:'Institution sync failed.')}finally{setSyncing(false)}}} disabled={syncing} className="btn-secondary px-4 py-2 text-sm shrink-0">{syncing?'Refreshing…':'Refresh institution catalogue'}</button>
   </div>
   <div className="grid md:grid-cols-3 gap-4 mt-6">
    <label className="space-y-2"><span className="text-sm font-semibold">Institution *</span><select value={selectedInstitution} onChange={e=>{const id=e.target.value;setSelectedInstitution(id);const inst=institutions.find(i=>i.id===id);setAnswers(v=>({...v,institution:inst?.name||''}))}} className="form-input"><option value="">Select institution</option>{['university','polytechnic'].map(type=><optgroup key={type} label={type==='university'?'Universities':'Polytechnics'}>{institutions.filter(i=>(i.institution_type||'university')===type).map(i=><option key={i.id} value={i.id}>{i.name}{i.ownership&&i.ownership!=='other'?' · '+i.ownership:''}</option>)}</optgroup>)}</select></label>
    <label className="space-y-2"><span className="text-sm font-semibold">Template name *</span><input value={name} onChange={e=>setName(e.target.value)} className="form-input" placeholder="Template or Template for this institution"/></label>
    <label className="space-y-2"><span className="text-sm font-semibold">Short description</span><input value={description} onChange={e=>setDescription(e.target.value)} className="form-input" placeholder="What this template is for"/></label>
   </div>
  </div>
  <div className="bento-card p-4 md:p-6">
   <div className="flex gap-2 overflow-x-auto pb-2 mb-6">{FINALYZED_DEFAULT_TEMPLATE.map((s,i)=><button key={s.title} onClick={()=>setStep(i)} className={'shrink-0 rounded-xl px-3 py-2 text-xs font-bold border '+(step===i?'bg-primary text-primary-foreground border-primary':'border-border text-muted-foreground')}>{i+1}. {s.title}</button>)}</div>
   <div className="flex items-start justify-between gap-4 mb-6"><div><span className="mono-label text-primary">Stage {step+1} of 13</span><h2 className="text-xl md:text-2xl font-bold mt-1">{current.title}</h2><p className="text-sm text-muted-foreground mt-2">{current.description}</p></div><div className="text-xs text-muted-foreground">{Object.values(answers).filter(v=>typeof v==='boolean'?true:Array.isArray(v)?v.length>0:String(v??'').trim()).length} answers</div></div>
   {errors.length>0&&<div className="mb-5 rounded-xl border border-red-500/20 bg-red-500/5 p-4 text-sm text-red-500">Please complete: {errors.join(', ')}</div>}
   <div className="grid grid-cols-1 md:grid-cols-2 gap-4">{current.fields.map(field=><React.Fragment key={field.key}><TemplateAnswerField field={field.key==='institution'?{...field,type:'text',placeholder:'Selected above'}:field} value={answers[field.key]} update={update}/></React.Fragment>) }</div>
   <div className="flex items-center justify-between gap-3 mt-8 pt-5 border-t border-border"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))} className="btn-secondary px-4 py-2 disabled:opacity-40">Previous</button>{step<12?<button onClick={()=>{if(validate())setStep(s=>s+1)}} className="btn-primary px-5 py-2">Next stage</button>:<button onClick={()=>void save()} disabled={saving||!selectedInstitution||!name.trim()} className="btn-primary px-5 py-2">{saving?'Publishing…':'Create Template'}</button>}</div>
  </div>
  {message&&<div className="bento-card p-4 text-sm border-primary/20 bg-primary/5">{message}</div>}
 </section>;
}

function TemplateAnswerField({field,value,update}:{field:TemplateField;value:any;update:(key:string,value:any)=>void}){
 const requiredMark=<span className="text-primary"> *</span>;
 if(field.type==='checkbox')return <fieldset className="md:col-span-2 space-y-2"><legend className="text-sm font-semibold">{field.label}{requiredMark}</legend><div className="grid grid-cols-2 gap-2">{[['yes',true],['no',false]].map(([label,choice]:any)=><label key={label} className={'flex items-center gap-2 rounded-xl border p-3 cursor-pointer '+(typeof value==='boolean'&&value===choice?'border-primary bg-primary/5':'border-border')}><input type="radio" name={field.key} checked={typeof value==='boolean'&&value===choice} onChange={()=>update(field.key,choice)} className="w-4 h-4"/><span className="text-sm font-semibold capitalize">{label}</span></label>)}</div></fieldset>;
 if(field.type==='textarea')return <label className="md:col-span-2 space-y-2"><span className="text-sm font-semibold">{field.label}{requiredMark}</span><textarea value={value??''} onChange={e=>update(field.key,e.target.value)} placeholder={field.placeholder||''} className="form-input min-h-[120px] resize-y"/></label>;
 if(field.type==='select')return <label className="space-y-2"><span className="text-sm font-semibold">{field.label}{requiredMark}</span><select value={value??''} onChange={e=>update(field.key,e.target.value)} className="form-input"><option value="">Select {field.label}</option>{(field.options||[]).map(o=><option key={o} value={o}>{o}</option>)}</select></label>;
 if(field.type==='multiselect')return <fieldset className="md:col-span-2 space-y-2"><legend className="text-sm font-semibold">{field.label}{requiredMark}</legend><div className="grid sm:grid-cols-2 gap-2">{(field.options||[]).map(o=><label key={o} className="flex items-center gap-3 rounded-xl border border-border p-3 cursor-pointer"><input type="checkbox" checked={Array.isArray(value)&&value.includes(o)} onChange={e=>update(field.key,e.target.checked?[...(Array.isArray(value)?value:[]),o]:(Array.isArray(value)?value:[]).filter(x=>x!==o))} className="w-4 h-4"/><span className="text-sm">{o}</span></label>)}</div></fieldset>;
 return <label className="space-y-2"><span className="text-sm font-semibold">{field.label}{requiredMark}</span><input type={field.type==='number'?'number':'text'} value={value??''} onChange={e=>update(field.key,e.target.value)} placeholder={field.placeholder||''} className="form-input"/></label>;
}
