import React from 'react';
import { CheckCircle2, Circle, FileText, Hash, Layers3, Ruler, ShieldCheck } from 'lucide-react';

type Specification = Record<string, unknown> | null;
type Props = { project: { id: string; title: string; plan: string; status: string; price_ngn?: number | null; price_points?: number | null }; specification: Specification };
const LABELS: Record<string, string> = { projectTitle:'Project title', project_title:'Project title', institution_id:'Institution ID', institutionId:'Institution ID', margins:'Margins', chapterCount:'Chapter count', chapter_count:'Chapter count', confirmed:'Confirmed', source_template_id:'Source template ID', sourceTemplateId:'Source template ID', source_template_name:'Source template name', sourceTemplateName:'Source template name', title:'Title', specification_schema:'Specification schema', specificationSchema:'Specification schema', answers:'Answers', status:'Status', is_complete:'Is complete', isComplete:'Is complete', project_details:'Project details', projectDetails:'Project details' };
const HIDDEN = new Set(['id','student_id','created_at','updated_at','confirmed_at']);
const label = (key:string) => LABELS[key] ?? key.replace(/([a-z])([A-Z])/g,'$1 $2').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase());
const valueText = (value:unknown) => { if(value===null||value===undefined||value==='') return 'Not provided'; if(typeof value==='boolean') return value?'Yes':'No'; if(typeof value==='object'){try{return JSON.stringify(value,null,2)}catch{return 'Structured value'}} return String(value); };
const pick = (spec:Specification,...keys:string[]) => { for(const key of keys){const value=spec?.[key]; if(value!==undefined&&value!==null&&value!=='') return value;} return undefined; };
const pointsFor = (project:Props['project'],spec:Specification) => { const explicit=pick(spec,'price_points','pricePoints','points','projectPoints'); if(typeof explicit==='number'&&explicit>=0)return explicit; if(typeof project.price_points==='number'&&project.price_points>=0)return project.price_points; return project.plan==='basic'?100:150; };
function StatusPill({value,positive=false}:{value:string;positive?:boolean}){return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-semibold ${positive?'border-primary/25 bg-primary/10 text-primary':'border-border bg-muted/40 text-foreground'}`}>{positive?<CheckCircle2 className="h-3.5 w-3.5"/>:<Circle className="h-3.5 w-3.5"/>}{value}</span>}
function Field({label,value,icon}:{label:string;value:unknown;icon?:React.ReactNode}){const objectValue=typeof value==='object'&&value!==null;return <div className="rounded-xl border border-border bg-background p-4"><div className="flex items-center gap-2 text-[10px] font-bold uppercase tracking-wider text-muted-foreground">{icon}{label}</div>{objectValue?<pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap break-words font-mono text-xs leading-5 text-foreground">{valueText(value)}</pre>:<div className="mt-1.5 break-words text-sm font-medium text-foreground">{valueText(value)}</div>}</div>}
export default function ProjectSpecificationSummary({project,specification}:Props){
 const title=pick(specification,'projectTitle','project_title')??project.title; const institutionId=pick(specification,'institution_id','institutionId'); const margins=pick(specification,'margins','marginLeft','margin_left'); const chapterCount=pick(specification,'chapterCount','chapter_count'); const confirmed=Boolean(pick(specification,'confirmed')); const sourceTemplateId=pick(specification,'source_template_id','sourceTemplateId'); const sourceTemplateName=pick(specification,'source_template_name','sourceTemplateName'); const sourceTitle=pick(specification,'title')??title; const schema=pick(specification,'specification_schema','specificationSchema'); const answers=pick(specification,'answers'); const specificationStatus=pick(specification,'status')??(confirmed?'CONFIRMED':'DRAFT'); const complete=Boolean(pick(specification,'is_complete','isComplete')); const details=pick(specification,'project_details','projectDetails'); const points=pointsFor(project,specification);
 const fields:Array<[string,unknown]>= [['projectTitle',title],['institution_id',institutionId],['margins',margins],['chapter_count',chapterCount],['source_template_id',sourceTemplateId],['source_template_name',sourceTemplateName],['title',sourceTitle],['specification_schema',schema],['answers',answers],['project_details',details]];
 const known=new Set([...fields.map(([key])=>key),'confirmed','status','is_complete']); const additional=Object.entries(specification||{}).filter(([key,v])=>!HIDDEN.has(key)&&!known.has(key)&&v!==null&&v!==undefined&&v!=='');
 return <section className="bento-card mb-6 overflow-hidden"><div className="border-b border-border bg-muted/20 p-6"><div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><div className="flex items-center gap-2 text-primary"><FileText className="h-5 w-5"/><span className="mono-label">PROJECT SPECIFICATION</span></div><h2 className="mt-2 text-lg font-bold md:text-xl">Project details & requirements</h2><p className="mt-1 text-sm text-muted-foreground">Structured commission data used by the writer and editor during delivery.</p></div><div className="rounded-xl border border-primary/20 bg-primary/5 px-4 py-3 text-right"><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Project price</div><div className="mt-0.5 text-lg font-bold text-primary">{points} Points</div></div></div></div><div className="p-6"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{fields.map(([key,v])=>{const icon=key==='institution_id'?<Hash className="h-3.5 w-3.5"/>:key==='margins'?<Ruler className="h-3.5 w-3.5"/>:key==='chapter_count'?<Layers3 className="h-3.5 w-3.5"/>:undefined;return <Field key={key} label={label(key)} value={v} icon={icon}/>})}</div><div className="mt-3 grid gap-3 sm:grid-cols-3"><div className="rounded-xl border border-border bg-background p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Status</div><div className="mt-2"><StatusPill value={String(specificationStatus)} positive={String(specificationStatus).toUpperCase()==='CONFIRMED'}/></div></div><div className="rounded-xl border border-border bg-background p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Confirmed</div><div className="mt-2"><StatusPill value={confirmed?'Confirmed':'Pending confirmation'} positive={confirmed}/></div></div><div className="rounded-xl border border-border bg-background p-4"><div className="text-[10px] font-bold uppercase tracking-wider text-muted-foreground">Completion</div><div className="mt-2"><StatusPill value={complete?'Complete':'Incomplete'} positive={complete}/></div></div></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-primary/15 bg-primary/5 p-4 text-sm text-muted-foreground"><ShieldCheck className="h-4 w-4 shrink-0 text-primary"/><span>These values are displayed from the stored project specification. The workspace does not silently rewrite commission requirements.</span></div>{additional.length>0&&<details className="mt-5 rounded-xl border border-border"><summary className="cursor-pointer list-none px-4 py-3 text-sm font-semibold">Additional specification fields ({additional.length})</summary><div className="grid gap-3 border-t border-border p-4 sm:grid-cols-2 lg:grid-cols-3">{additional.slice(0,30).map(([key,v])=><Field key={key} label={label(key)} value={v}/>)}</div></details>}</div></section>;
}
