import React,{useEffect,useState} from 'react';
import {CheckCircle2,Plus,Trash2,Save,Building2} from 'lucide-react';
import {supabase} from '../lib/supabase';

export type TemplateField={key:string;label:string;type:'text'|'textarea'|'select'|'number'|'checkbox'|'multiselect';placeholder?:string;required?:boolean;options?:string[]};
export type TemplateStep={title:string;description:string;fields:TemplateField[]};

export const FINALYZED_DEFAULT_TEMPLATE:TemplateStep[]=[
{title:'Student Information',description:'Academic identity and submission context.',fields:[
{key:'fullName',label:'Full name',type:'text',required:true},{key:'matricNumber',label:'Matriculation / registration number',type:'text',required:true},{key:'institution',label:'Institution',type:'select',required:true},{key:'faculty',label:'Faculty / school',type:'text',required:true},{key:'department',label:'Department',type:'text',required:true},{key:'degree',label:'Degree / award',type:'select',required:true,options:['ND','HND','BSc','BA','BEng','BTech','LLB','MBBS','MSc','MA','MEng','Other']},{key:'supervisor',label:'Project supervisor',type:'text'},{key:'hod',label:'Head of department',type:'text'},{key:'submissionMonth',label:'Submission month',type:'select',options:['January','February','March','April','May','June','July','August','September','October','November','December']},{key:'submissionYear',label:'Submission year',type:'select',options:Array.from({length:10},(_,i)=>String(new Date().getFullYear()+i))}]},
{title:'Project Identity',description:'What the specialist is being commissioned to deliver.',fields:[
{key:'projectTitle',label:'Exact approved project title',type:'text',required:true},{key:'projectType',label:'Project type',type:'select',required:true,options:['Design & Construction','Research Study','Software Development','Case Study','Business Plan','Survey-Based Study','Literature Review','Other']},{key:'subjectArea',label:'Core subject matter / technology / method',type:'text'},{key:'problemStatement',label:'Problem being addressed',type:'textarea'},{key:'aimObjectives',label:'Aim and objectives',type:'textarea'},{key:'expectedOutcome',label:'Target outcome / result',type:'textarea'},{key:'supervisorInstructions',label:'Supervisor instructions',type:'textarea'},{key:'topicApproved',label:'Topic officially approved?',type:'checkbox'}]},
{title:'Institution Requirements',description:'Department-specific rules become part of the QA checklist.',fields:[
{key:'hasPrescribedFormat',label:'Does your institution have a prescribed project format?',type:'select',options:['Yes','No','Unknown']},{key:'prescribedFormatDetails',label:'Prescribed format details',type:'textarea'},{key:'preliminaryPages',label:'Required preliminary pages',type:'textarea',placeholder:'Certification, Dedication, Acknowledgement, Abstract, TOC…'},{key:'institutionStructure',label:'Required chapter structure / department rules',type:'textarea'},{key:'standardsBodies',label:'Relevant standards / regulatory bodies',type:'textarea'},{key:'ethicalRequirements',label:'Ethical, safety, data-protection or institutional requirements',type:'textarea'}]},
{title:'Formatting',description:'Formatting rules used by writers and editors.',fields:[
{key:'fontFamily',label:'Font family',type:'select',options:['Times New Roman','Arial','Calibri','Georgia','Institution Standard','Other']},{key:'bodyFontSize',label:'Body font size (pt)',type:'select',options:['10','11','12','13','14']},{key:'headingFontSize',label:'Heading font size (pt)',type:'select',options:['12','13','14','15','16','18']},{key:'lineSpacing',label:'Line spacing',type:'select',options:['1.0','1.15','1.5','2.0','Institution Standard']},{key:'alignment',label:'Body alignment',type:'select',options:['Justified','Left','Institution Standard']},{key:'paragraphIndentation',label:'Paragraph indentation',type:'select',options:['None','0.25 inch','0.5 inch','1 inch','Institution Standard']},{key:'marginLeft',label:'Left margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginRight',label:'Right margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginTop',label:'Top margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'marginBottom',label:'Bottom margin (inch)',type:'select',options:['0.5','0.75','1','1.25','1.5','2']},{key:'preliminaryNumbering',label:'Preliminary numbering',type:'select',options:['Roman numerals','Arabic numerals','Institution Standard']},{key:'chapterNumbering',label:'Chapter numbering',type:'select',options:['Arabic numerals','Institution Standard']},{key:'headerFooterRules',label:'Header / footer rules',type:'textarea'},{key:'tableFigureRules',label:'Table / figure / caption rules',type:'textarea'}]},
{title:'Page & Length',description:'Requested length and page-budget rules.',fields:[
{key:'minPages',label:'Minimum pages',type:'number'},{key:'targetPages',label:'Target pages',type:'number',required:true},{key:'maxPages',label:'Maximum pages',type:'number'},{key:'countPrelim',label:'Preliminary pages count',type:'checkbox'},{key:'countReferences',label:'References count',type:'checkbox'},{key:'countAppendices',label:'Appendices count',type:'checkbox'},{key:'pageBudgetInstructions',label:'Page-budget / length instructions',type:'textarea'}]},
{title:'Structure',description:'Define the chapter architecture.',fields:[
{key:'chapterCount',label:'Number of chapters',type:'select',options:['3','4','5','6','7','8']},{key:'mandatorySubsections',label:'Mandatory sections / subsections',type:'textarea'},{key:'excludedSections',label:'Sections that must be excluded',type:'textarea'}]},
{title:'Citation & References',description:'Citation style and source requirements.',fields:[
{key:'citationStyle',label:'Citation style',type:'select',required:true,options:['APA 7th','IEEE','Harvard','MLA','Vancouver','Chicago','Institution Standard','Other']},{key:'minReferences',label:'Minimum references',type:'number'},{key:'maxReferences',label:'Maximum references',type:'number'},{key:'sourceRequirements',label:'Source requirements',type:'textarea'},{key:'requiredReferences',label:'Required standards / datasheets / regulatory references',type:'textarea'}]},
{title:'Methodology / Design',description:'How the work should be conducted, built, tested or analysed.',fields:[
{key:'methodology',label:'Methodology / research design / system architecture',type:'textarea',required:true},{key:'technologies',label:'Required technologies / instruments / tools',type:'text'},{key:'scope',label:'Population, sample, scope or system boundary',type:'textarea'},{key:'dataCollectionMethod',label:'Sampling / data collection method',type:'textarea'},{key:'analysisMethod',label:'Analysis / calculation / testing method',type:'textarea'},{key:'complianceApproach',label:'Safety, ethical and regulatory compliance approach',type:'textarea'},{key:'designJustification',label:'Design decisions and justification',type:'textarea'}]},
{title:'Data & Results',description:'Evidence and measurable outcomes.',fields:[
{key:'hasRealData',label:'Do you already have real project data?',type:'select',options:['Yes','No','Partial']},{key:'availableData',label:'Available data / results',type:'textarea'},{key:'resultRequirements',label:'Expected results, tables, charts, diagrams or technical drawings',type:'textarea'},{key:'targetOutcomeMetric',label:'Target performance / measurable outcome',type:'text'},{key:'testingRequirements',label:'Testing / validation requirements',type:'textarea'}]},
{title:'Appendices',description:'Supporting material for the final deliverable.',fields:[
{key:'appendices',label:'Appendices required',type:'multiselect',options:['Questionnaire','Interview Questions','Test Log','Bill of Materials','Budget','Code Listing','Technical Drawings','Financial Statements','Reference Tables','Implementation Timeline']},{key:'otherAppendices',label:'Other appendices',type:'text'},{key:'appendixInstructions',label:'Appendix-specific instructions',type:'textarea'}]},
{title:'Presentation',description:'Presentation deliverables.',fields:[
{key:'presentationRequired',label:'Project presentation is required',type:'checkbox'},{key:'slideCount',label:'Expected slide count',type:'select',options:['10–15','15–20','20–25','25–30','30+']},{key:'presentationStyle',label:'Presentation style',type:'select',options:['Academic defence','Institution template','Minimal professional','Other']},{key:'defenceRequirements',label:'Defence requirements / likely questions',type:'textarea'},{key:'presentationGuideRequired',label:'Simplified presentation guide is required',type:'checkbox'}]},
{title:'Special Instructions',description:'Anything important that does not fit elsewhere.',fields:[
{key:'specialInstructions',label:'Special instructions',type:'textarea'},{key:'doNotChange',label:'Things the writer must NOT change',type:'textarea'},{key:'deliveryInstructions',label:'Expected communication / delivery instructions',type:'textarea'},{key:'otherNotes',label:'Other notes from supervisor or department',type:'textarea'}]}
];

export default function ProjectTemplateManager(){
 const [institutions,setInstitutions]=useState<any[]>([]); const [selectedInstitution,setSelectedInstitution]=useState(''); const [name,setName]=useState(''); const [description,setDescription]=useState(''); const [schema,setSchema]=useState<TemplateStep[]>(FINALYZED_DEFAULT_TEMPLATE); const [saving,setSaving]=useState(false); const [syncing,setSyncing]=useState(false); const [message,setMessage]=useState('');
 useEffect(()=>{void loadInstitutions()},[]);
 const loadInstitutions=async()=>{const {data}=await supabase.from('institutions').select('id,name,ownership,state,verified').order('name');setInstitutions(data||[])};
 const updateField=(si:number,fi:number,patch:Partial<TemplateField>)=>setSchema(s=>s.map((st,i)=>i===si?{...st,fields:st.fields.map((f,j)=>j===fi?{...f,...patch}:f)}:st));
 const addField=(si:number)=>setSchema(s=>s.map((st,i)=>i===si?{...st,fields:[...st.fields,{key:'custom_'+Date.now(),label:'New question',type:'text'}]}:st));
 const removeField=(si:number,fi:number)=>setSchema(s=>s.map((st,i)=>i===si?{...st,fields:st.fields.filter((_,j)=>j!==fi)}:st));
 const syncNUC=async()=>{setSyncing(true);setMessage('Scanning the current NUC federal, state and private university lists…');try{const r=await fetch('/.netlify/functions/nuc-universities');const payload=await r.json();if(!r.ok)throw new Error(payload.error||'NUC sync failed.');const result=await supabase.rpc('admin_import_institutions',{p_institutions:payload.institutions});if(result.error)throw result.error;await loadInstitutions();setMessage('NUC sync complete: '+String(result.data?.inserted||0)+' added, '+String(result.data?.updated||0)+' refreshed.');}catch(e){setMessage(e instanceof Error?e.message:'NUC sync failed.')}finally{setSyncing(false)}};
 const save=async()=>{if(!selectedInstitution||!name.trim()){setMessage('Choose an institution and name the template.');return}setSaving(true);setMessage('');
 const {error}=await supabase.from('institution_templates').insert({institution_id:selectedInstitution,name:name.trim(),description:description.trim(),specification_schema:schema,specification_defaults:{},verified:true});
 setSaving(false);setMessage(error?error.message:'Template published successfully.');};
 return <section className="bento-card p-6 space-y-6">
  <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4"><div><div className="mono-label text-primary flex items-center gap-2"><Building2 className="w-4 h-4"/>Project Template Studio</div><h2 className="text-2xl font-bold mt-2">Build the student specification form</h2><p className="text-sm text-muted-foreground mt-2 max-w-3xl">Every question configured here becomes part of the student's project specification. Use structured controls instead of forcing students to type everything manually.</p></div><div className="flex gap-2"><button onClick={()=>void syncNUC()} disabled={syncing} className="btn-secondary px-4 py-2 text-sm">{syncing?'Syncing NUC…':'Sync NUC universities'}</button><button onClick={()=>setSchema(FINALYZED_DEFAULT_TEMPLATE)} className="btn-secondary px-4 py-2 text-sm">Reset to Finalyzed baseline</button></div></div>
  <div className="grid md:grid-cols-3 gap-4"><label className="block space-y-2"><span className="text-sm font-semibold">Institution</span><select value={selectedInstitution} onChange={e=>setSelectedInstitution(e.target.value)} className="form-input"><option value="">Select institution</option>{institutions.map(i=><option key={i.id} value={i.id}>{i.name}{i.ownership&&i.ownership!=='other'?' · '+i.ownership:''}</option>)}</select></label><label className="block space-y-2"><span className="text-sm font-semibold">Template name</span><input value={name} onChange={e=>setName(e.target.value)} className="form-input" placeholder="e.g. BSc Computer Science — Project Template"/></label><label className="block space-y-2"><span className="text-sm font-semibold">Description</span><input value={description} onChange={e=>setDescription(e.target.value)} className="form-input" placeholder="Rules this template captures"/></label></div>
  <div className="space-y-4">{schema.map((step,si)=><div key={step.title} className="rounded-2xl border border-border p-4"><div className="flex items-center justify-between gap-3 mb-4"><div><h3 className="font-bold">{si+1}. {step.title}</h3><p className="text-xs text-muted-foreground">{step.description}</p></div><button onClick={()=>addField(si)} className="btn-secondary px-3 py-2 text-xs flex items-center gap-1"><Plus className="w-3 h-3"/>Question</button></div><div className="space-y-2">{step.fields.map((field,fi)=><div key={field.key} className="grid grid-cols-1 lg:grid-cols-[1fr_150px_1fr_auto] gap-2 items-center rounded-xl bg-muted/30 p-3"><input value={field.label} onChange={e=>updateField(si,fi,{label:e.target.value})} className="form-input text-sm" placeholder="Question label"/><select value={field.type} onChange={e=>updateField(si,fi,{type:e.target.value as TemplateField['type']})} className="form-input text-sm"><option value="text">Short text</option><option value="textarea">Long text</option><option value="select">Dropdown</option><option value="number">Number</option><option value="checkbox">Checkbox</option><option value="multiselect">Multi-select</option></select><input value={(field.options||[]).join(' | ')} onChange={e=>updateField(si,fi,{options:e.target.value.split('|').map(x=>x.trim()).filter(Boolean)})} disabled={!['select','multiselect'].includes(field.type)} className="form-input text-sm disabled:opacity-30" placeholder="Options: Option A | Option B"/><div className="flex items-center gap-2"><label className="flex items-center gap-1 text-xs"><input type="checkbox" checked={Boolean(field.required)} onChange={e=>updateField(si,fi,{required:e.target.checked})}/>Required</label><button onClick={()=>removeField(si,fi)} className="p-2 text-red-500 hover:bg-red-500/10 rounded-lg" aria-label="Remove question"><Trash2 className="w-4 h-4"/></button></div></div>)}</div></div>)}</div>
  {message&&<div className="rounded-xl border border-primary/20 bg-primary/5 p-4 text-sm flex items-center gap-2"><CheckCircle2 className="w-4 h-4 text-primary"/>{message}</div>}
  <button onClick={()=>void save()} disabled={saving||!selectedInstitution||!name.trim()} className="btn-primary w-full py-3 flex items-center justify-center gap-2 disabled:opacity-50"><Save className="w-4 h-4"/>{saving?'Publishing…':'Publish Project Template'}</button>
 </section>;
}  const syncNUC=async()=>{
    setSyncing(true);
    setMessage('Scanning the current NUC federal, state and private university lists…');
    try {
      const r=await fetch('/.netlify/functions/nuc-universities');
      const payload=await r.json();
      if(!r.ok) throw new Error(payload.error||'NUC sync failed.');
      const result=await supabase.rpc('admin_import_institutions',{p_institutions:payload.institutions});
      if(result.error) throw result.error;
      await loadInstitutions();
      setMessage('NUC sync complete: '+String(result.data?.inserted||0)+' added, '+String(result.data?.updated||0)+' refreshed.');
    } catch(e) {
      setMessage(e instanceof Error?e.message:'NUC sync failed.');
    } finally {
      setSyncing(false);
    }
  };
