import React,{useEffect,useState} from 'react';
import {Activity,BarChart3,CheckCircle2,DollarSign,FileCheck2,FolderKanban,MessageSquare,ShieldCheck,Users,Wallet as WalletIcon,Zap} from 'lucide-react';
import {supabase} from '../lib/supabase';
type Props={role:string;userId?:string};
const money=(n:number)=>'₦'+Number(n||0).toLocaleString('en-NG');
export default function RoleOperationsOverview({role,userId}:Props){
 const [stats,setStats]=useState<any>(null); const [loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;(async()=>{try{
  if(role==='admin'){const [s,p,w]=await Promise.all([supabase.rpc('finalyzed_admin_stats'),supabase.from('projects').select('status,created_at'),supabase.from('withdrawals').select('status,amount_ngn')]);if(live)setStats({...((s.data as any)||{}),projects:p.data||[],withdrawals:w.data||[]});}
  else if(userId){let pq=supabase.from('projects').select('id,status,plan,price_ngn,created_at,deadline_at');if(role==='student')pq=pq.eq('student_id',userId);else if(role==='writer')pq=pq.eq('writer_id',userId);else pq=pq.eq('editor_id',userId);const [p,r,w]=await Promise.all([pq.order('created_at',{ascending:false}),supabase.from('project_revisions').select('id,status,project_id,created_at').order('created_at',{ascending:false}).limit(100),supabase.from('wallets').select('balance_ngn,points_balance').eq('user_id',userId).maybeSingle()]);const projects=p.data||[];const ids=new Set(projects.map((x:any)=>x.id));const revisions=(r.data||[]).filter((x:any)=>ids.has(x.project_id));if(live)setStats({projects,revisions,wallet:w.data||{balance_ngn:0,points_balance:0}});}
 }finally{if(live)setLoading(false)}})();return()=>{live=false}},[role,userId]);
 if(loading)return null;
 if(role==='admin'){const projects=stats?.projects||[];const total=Math.max(1,projects.length);const statuses=['paid','in_progress','submitted_for_review','revision_requested','completed','disputed'];return <section className="space-y-5">
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-4"><OpsMetric icon={<Users/>} label="Students" value={stats?.students||0}/><OpsMetric icon={<ShieldCheck/>} label="Managers" value={stats?.managers||0}/><OpsMetric icon={<Users/>} label="Writers" value={stats?.writers||0}/><OpsMetric icon={<Activity/>} label="Projects tracked" value={projects.length}/></div>
  <div className="grid lg:grid-cols-2 gap-5"><div className="bento-card p-6"><div className="flex items-center gap-3 mb-5"><BarChart3 className="w-5 h-5 text-primary"/><div><h2 className="font-bold">Platform activity</h2><p className="text-xs text-muted-foreground">Live project distribution by workflow stage.</p></div></div><div className="space-y-3">{statuses.map(s=>{const n=projects.filter((p:any)=>p.status===s).length;return <div key={s}><div className="flex justify-between text-xs mb-1"><span className="capitalize">{s.replaceAll('_',' ')}</span><b>{n}</b></div><div className="h-2 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary rounded-full" style={{width:(n/total*100)+'%'}}/></div></div>})}</div></div>
  <div className="bento-card p-6"><div className="flex items-center gap-3 mb-5"><DollarSign className="w-5 h-5 text-primary"/><div><h2 className="font-bold">Financial control</h2><p className="text-xs text-muted-foreground">Revenue and withdrawal pressure points.</p></div></div><div className="grid grid-cols-2 gap-3"><SmallStat label="Verified revenue" value={money(stats?.total_revenue_ngn||0)}/><SmallStat label="Pending withdrawals" value={String((stats?.withdrawals||[]).filter((x:any)=>x.status==='pending').length)}/><SmallStat label="Active projects" value={String(projects.filter((x:any)=>!['completed','cancelled'].includes(x.status)).length)}/><SmallStat label="Disputes" value={String(projects.filter((x:any)=>x.status==='disputed').length)}/></div></div></div>
  <div className="bento-card p-5 flex flex-wrap items-center gap-3 text-sm"><span className="font-semibold flex items-center gap-2"><Zap className="w-4 h-4 text-primary"/>Admin control centre</span><span className="text-muted-foreground">Monitor assignments, QA, applications, payments, withdrawals and service warnings from the sections below.</span></div>
 </section>}
 const projects=stats?.projects||[];const revisions=stats?.revisions||[];const pending=role==='editor'?projects.filter((p:any)=>p.status==='submitted_for_review').length:revisions.filter((r:any)=>['requested','pending','accepted'].includes(r.status)).length;
 return <section className="grid grid-cols-2 lg:grid-cols-3 gap-4"><OpsMetric icon={<roleIcon role={role}/>} label={role==='editor'?'QA queue':'Revision activity'} value={pending}/><OpsMetric icon={<CheckCircle2/>} label="Completed" value={projects.filter((p:any)=>p.status==='completed').length}/><OpsMetric icon={<WalletIcon/>} label="Points balance" value={Number(stats?.wallet?.points_balance||0).toLocaleString()}/></section>;
}
function roleIcon({role}:{role:string}){return role==='editor'?<FileCheck2/>:<MessageSquare/>}
function OpsMetric({icon,label,value}:{icon:React.ReactNode;label:string;value:number|string}){return <div className="bento-card p-5"><div className="text-primary">{icon}</div><p className="text-[10px] uppercase tracking-wider text-muted-foreground mt-3">{label}</p><p className="text-2xl font-bold mt-1">{value}</p></div>}
function SmallStat({label,value}:{label:string;value:string}){return <div className="rounded-xl border border-border p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="font-bold mt-1">{value}</p></div>}
