import React,{useEffect,useMemo,useState} from 'react';
import {CheckCircle,Clock,Coins,Send,XCircle} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Props={projects:any[];wallet:any;userId:string;onChanged?:()=>void};
type Writer={id:string;display_name:string;rating?:number|null};
type Commission={id:string;project_id:string;from_writer_id:string;to_writer_id:string;points:number;deadline_at:string;note:string|null;status:string;created_at:string};

export default function WriterCommissionPanel({projects,wallet,userId,onChanged}:Props){
 const [writers,setWriters]=useState<Writer[]>([]);const [history,setHistory]=useState<Commission[]>([]);const [projectId,setProjectId]=useState('');const [writerId,setWriterId]=useState('');const [points,setPoints]=useState('');const [deadline,setDeadline]=useState('');const [note,setNote]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [message,setMessage]=useState('');
 const load=async()=>{const [{data:w},{data:c,error:ce}]=await Promise.all([supabase.from('public_profiles').select('id,display_name,rating').eq('verified',true).order('rating',{ascending:false}),supabase.rpc('get_my_writer_commissions')]);if(ce){setError(ce.message);return}setWriters((w||[]).filter(x=>x.id!==userId));setHistory(c||[])};
 useEffect(()=>{void load()},[userId]);
 const selected=useMemo(()=>projects.find(p=>p.id===projectId),[projects,projectId]);
 useEffect(()=>{if(selected?.deadline_at)setDeadline(new Date(selected.deadline_at).toISOString().slice(0,16));},[selected]);
 const submit=async()=>{setBusy(true);setError('');setMessage('');try{const amount=Number(points);if(!projectId||!writerId||!Number.isInteger(amount)||amount<10||!deadline)throw new Error('Select a project, writer, payment of at least 10 Points, and a deadline.');const {error:e}=await supabase.rpc('commission_project_to_writer',{p_project_id:projectId,p_to_writer_id:writerId,p_points:amount,p_deadline_at:new Date(deadline).toISOString(),p_note:note.trim()||null});if(e)throw e;setMessage('Commission sent. The selected writer has been notified; your Points are refunded automatically if they decline.');setProjectId('');setWriterId('');setPoints('');setDeadline('');setNote('');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to send commission.')}finally{setBusy(false)}};
 const respond=async(id:string,accept:boolean)=>{setBusy(true);setError('');try{const {error:e}=await supabase.rpc('respond_to_writer_commission',{p_commission_id:id,p_accept:accept});if(e)throw e;setMessage(accept?'Commission accepted. The project is now active and the Points have been released to you.':'Commission declined. The sender has been refunded.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to update commission.')}finally{setBusy(false)}};
 const cancel=async(id:string)=>{setBusy(true);setError('');try{const {error:e}=await supabase.rpc('cancel_writer_commission',{p_commission_id:id});if(e)throw e;setMessage('Commission cancelled and Points refunded.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to cancel commission.')}finally{setBusy(false)}};
 const names=useMemo(()=>new Map(writers.map(w=>[w.id,w.display_name||'Finalyzed Writer'])),[writers]);
 const sent=(c:Commission)=>c.from_writer_id===userId;const received=(c:Commission)=>c.to_writer_id===userId;
 return <section className='bento-card p-6 md:p-7'>
  <div><div className='flex items-center gap-2 text-primary'><Send className='w-5 h-5'/><span className='mono-label'>WRITER COMMISSION</span></div><h2 className='text-xl md:text-2xl font-bold mt-2'>Commission work to another writer</h2><p className='text-sm text-muted-foreground mt-1'>Delegate one of your active projects to an approved writer and pay them in Finalyzed Points. Points are held until the receiving writer accepts.</p></div>
  <div className='grid gap-3 md:grid-cols-2 mt-6'><select value={projectId} onChange={e=>setProjectId(e.target.value)} className='form-input'><option value=''>Select active project</option>{projects.filter(p=>['assigned','in_progress','revision_in_progress','editor_correction_required'].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.title} · {p.status.replace(/_/g,' ')}</option>)}</select><select value={writerId} onChange={e=>setWriterId(e.target.value)} className='form-input'><option value=''>Select approved writer</option>{writers.map(w=><option key={w.id} value={w.id}>{w.display_name||'Finalyzed Writer'}{w.rating?` · ${Number(w.rating).toFixed(1)}★`:''}</option>)}</select><input value={points} onChange={e=>setPoints(e.target.value.replace(/\D/g,''))} inputMode='numeric' min='10' placeholder='Payment in Finalyzed Points (min. 10)' className='form-input'/><input type='datetime-local' value={deadline} onChange={e=>setDeadline(e.target.value)} className='form-input'/></div>
  <textarea value={note} onChange={e=>setNote(e.target.value)} placeholder='Optional instructions for the receiving writer' className='form-input min-h-24 mt-3'/>
  {selected&&<p className='text-xs text-muted-foreground mt-2'>Original deadline: {selected.deadline_at?new Date(selected.deadline_at).toLocaleString('en-NG'):'not set'}. The commission deadline cannot extend beyond it.</p>}
  <div className='mt-3 flex items-center justify-between rounded-xl border border-primary/20 bg-primary/5 px-4 py-3'><span className='text-xs text-muted-foreground'>Your available Points</span><span className='font-bold text-primary flex items-center gap-1'><Coins className='w-4 h-4'/>{Number(wallet?.points_balance||0).toLocaleString()}</span></div>
  {error&&<div className='mt-4 rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-500'>{error}</div>}{message&&<div className='mt-4 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary'>{message}</div>}
  <button disabled={busy||!projectId||!writerId||!points||!deadline} onClick={submit} className='btn-primary mt-4 w-full md:w-auto px-6 py-3 disabled:opacity-50'>{busy?'Processing…':'Send Commission'}</button>
  <div className='mt-8 pt-6 border-t border-border'><h3 className='font-bold mb-3'>Commission history</h3>{history.length===0?<p className='text-sm text-muted-foreground'>No writer commissions yet.</p>:<div className='space-y-3'>{history.map(c=><div key={c.id} className='rounded-xl border border-border p-4'><div className='flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3'><div><p className='font-semibold'>{sent(c)?`To ${names.get(c.to_writer_id)||'Writer'}`:`From ${names.get(c.from_writer_id)||'Writer'}`}</p><p className='text-xs text-muted-foreground mt-1'>{c.points} Points · deadline {new Date(c.deadline_at).toLocaleString('en-NG')}</p></div><span className='text-xs uppercase font-bold text-primary'>{c.status}</span></div>{c.note&&<p className='text-sm text-muted-foreground mt-2'>{c.note}</p>}{c.status==='pending'&&received(c)&&<div className='flex flex-wrap gap-2 mt-3'><button disabled={busy} onClick={()=>respond(c.id,true)} className='btn-primary px-4 py-2 text-xs'><CheckCircle className='w-3.5 h-3.5 inline mr-1'/>Accept</button><button disabled={busy} onClick={()=>respond(c.id,false)} className='rounded-lg border border-red-500/30 text-red-500 px-4 py-2 text-xs font-bold'><XCircle className='w-3.5 h-3.5 inline mr-1'/>Decline</button></div>}{c.status==='pending'&&sent(c)&&<button disabled={busy} onClick={()=>cancel(c.id)} className='btn-secondary mt-3 px-4 py-2 text-xs'><Clock className='w-3.5 h-3.5 inline mr-1'/>Cancel & refund</button>}</div>)}</div>}</div>
 </section>;
}
