import React,{useEffect,useState} from 'react';
import {ArrowRightLeft,CheckCircle,Clock,XCircle} from 'lucide-react';
import {supabase} from '../lib/supabase';

type Props={projects:any[];userId:string;onChanged?:()=>void};
type Writer={id:string;display_name:string;rating?:number|null};
type Transfer={id:string;project_id:string;from_writer_id:string;to_writer_id:string;deadline_at:string;note:string|null;status:string;created_at:string};

export default function WriterProjectTransferPanel({projects,userId,onChanged}:Props){
 const [writers,setWriters]=useState<Writer[]>([]),[history,setHistory]=useState<Transfer[]>([]),[projectId,setProjectId]=useState(''),[writerId,setWriterId]=useState(''),[deadline,setDeadline]=useState(''),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const load=async()=>{const [{data:w,error:we},{data:t,error:te}]=await Promise.all([supabase.from('public_profiles').select('id,display_name,rating').eq('verified',true).order('rating',{ascending:false}),supabase.rpc('get_my_writer_transfers')]);if(we)throw we;if(te)throw te;setWriters((w||[]).filter(x=>x.id!==userId));setHistory(t||[])};
 useEffect(()=>{load().catch(e=>setError(e instanceof Error?e.message:'Unable to load transfers.'))},[userId]);
 const selected=projects.find(p=>p.id===projectId);
 useEffect(()=>{if(selected?.deadline_at)setDeadline(new Date(selected.deadline_at).toISOString().slice(0,16))},[selected]);
 const send=async()=>{setBusy(true);setError('');setMessage('');try{if(!projectId||!writerId||!deadline)throw new Error('Select a project, writer and deadline.');const {error:e}=await supabase.rpc('transfer_project_to_writer',{p_project_id:projectId,p_to_writer_id:writerId,p_deadline_at:new Date(deadline).toISOString(),p_note:note.trim()||null});if(e)throw e;setMessage('Transfer request sent. The selected writer must accept before the project becomes theirs.');setProjectId('');setWriterId('');setDeadline('');setNote('');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to transfer project.')}finally{setBusy(false)}};
 const respond=async(id:string,accept:boolean)=>{setBusy(true);setError('');try{const {error:e}=await supabase.rpc('respond_to_writer_transfer',{p_transfer_id:id,p_accept:accept});if(e)throw e;setMessage(accept?'Transfer accepted. The project is now in your workspace.':'Transfer declined. The project remains with the original writer.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to update transfer.')}finally{setBusy(false)}};
 const cancel=async(id:string)=>{setBusy(true);setError('');try{const {error:e}=await supabase.rpc('cancel_writer_transfer',{p_transfer_id:id});if(e)throw e;setMessage('Transfer cancelled.');await load();onChanged?.()}catch(e){setError(e instanceof Error?e.message:'Unable to cancel transfer.')}finally{setBusy(false)}};
 const name=new Map(writers.map(w=>[w.id,w.display_name||'Finalyzed Writer']));
 return <section className='bento-card p-6 md:p-7'>
  <div className='flex items-center gap-2 text-primary'><ArrowRightLeft className='w-5 h-5'/><span className='mono-label'>PROJECT TRANSFER</span></div><h2 className='text-xl md:text-2xl font-bold mt-2'>Transfer a project to another writer</h2><p className='text-sm text-muted-foreground mt-1'>Hand an active project to another approved writer without a Coin payment. The receiving writer must accept first.</p>
  <div className='grid gap-3 md:grid-cols-2 mt-6'><select value={projectId} onChange={e=>setProjectId(e.target.value)} className='form-input'><option value=''>Select active project</option>{projects.filter(p=>['assigned','in_progress','revision_in_progress','editor_correction_required'].includes(p.status)).map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select><select value={writerId} onChange={e=>setWriterId(e.target.value)} className='form-input'><option value=''>Select approved writer</option>{writers.map(w=><option key={w.id} value={w.id}>{w.display_name||'Finalyzed Writer'}{w.rating?` · ${Number(w.rating).toFixed(1)}★`:''}</option>)}</select><input type='datetime-local' value={deadline} onChange={e=>setDeadline(e.target.value)} className='form-input'/></div>
  <textarea value={note} onChange={e=>setNote(e.target.value)} placeholder='Optional handover instructions' className='form-input min-h-24 mt-3'/>{selected&&<p className='text-xs text-muted-foreground mt-2'>The transfer deadline cannot be later than the current project deadline.</p>}
  {error&&<div className='mt-4 rounded-xl border border-red-500/20 bg-red-500/5 p-3 text-sm text-red-500'>{error}</div>}{message&&<div className='mt-4 rounded-xl border border-primary/20 bg-primary/5 p-3 text-sm text-primary'>{message}</div>}
  <button disabled={busy||!projectId||!writerId||!deadline} onClick={send} className='btn-primary mt-4 px-6 py-3'>{busy?'Processing…':'Send Transfer'}</button>
  <div className='mt-8 pt-6 border-t border-border'><h3 className='font-bold mb-3'>Transfer history</h3>{history.length===0?<p className='text-sm text-muted-foreground'>No project transfers yet.</p>:<div className='space-y-3'>{history.map(t=><div key={t.id} className='rounded-xl border border-border p-4'><div className='flex justify-between gap-3'><div><p className='font-semibold'>{t.from_writer_id===userId?`To ${name.get(t.to_writer_id)||'Writer'}`:`From ${name.get(t.from_writer_id)||'Writer'}`}</p><p className='text-xs text-muted-foreground mt-1'>Deadline {new Date(t.deadline_at).toLocaleString('en-NG')}</p></div><span className='text-xs uppercase font-bold text-primary'>{t.status}</span></div>{t.note&&<p className='text-sm text-muted-foreground mt-2'>{t.note}</p>}{t.status==='pending'&&t.to_writer_id===userId&&<div className='flex gap-2 mt-3'><button disabled={busy} onClick={()=>respond(t.id,true)} className='btn-primary px-4 py-2 text-xs'><CheckCircle className='w-3.5 h-3.5 inline mr-1'/>Accept</button><button disabled={busy} onClick={()=>respond(t.id,false)} className='rounded-lg border border-red-500/30 text-red-500 px-4 py-2 text-xs font-bold'><XCircle className='w-3.5 h-3.5 inline mr-1'/>Decline</button></div>}{t.status==='pending'&&t.from_writer_id===userId&&<button disabled={busy} onClick={()=>cancel(t.id)} className='btn-secondary mt-3 px-4 py-2 text-xs'><Clock className='w-3.5 h-3.5 inline mr-1'/>Cancel</button>}</div>)}</div>}</div>
 </section>;
}
